- src/zero/api/handlers.clj
Currently, if you are not logged in the WFL API returns a redirect response. However, swagger will return `{"status":"ok"}` in this case, presumably because the redirect was successful. This is confusing behavior because it makes it seem like the request itself was successful.
Make the `authorize` function return a 401 error if a user is not logged in.
> Return 401 error when logged out

- src/zero/api/handlers.clj
The WFL API is only checking requests for a google oauth access token.
Update the `authenticate` fn to check if the authorization header of an incoming request contains a token.
> Check authorization headers in API requests

- src/zero/api/routes.clj
- src/zero/module/wgs.clj
The expected response type of the `wgs` endpoint (seq) does not match what is returned by the handler (nil) which causes an error. Also if no information is returned about the workflows/workload that was started, then there is no way to track the progress of that work and test that it was successful.
Update this endpoint to return a vector of workflow ids instead of nil. 
~Note: This breaks the command line so it's still a WIP~
> Update WGS endpoint response

- build.boot
- deps.edn
- integration/zero/wgs_test.clj
- src/zero/service/cromwell.clj
- src/zero/service/gcs.clj
Add an integration test that sends a request to the `wgs` endpoint and checks that the resulting test workflow succeeds: https://broadinstitute.atlassian.net/jira/software/projects/GH/boards/530?selectedIssue=GH-640
Add a `wgs_test.clj` file that can be run with the command:
`clojure -A:integration <cromwell-env> <max> <input_path> <output_path>`
Note: `cromwell/wait-for-workflow-complete` gets the cromwell url out of the wfl `env`, which is why I included `resources` in the extra paths instead of just `integration`. There is probably a better way to do this...
To-Do:
> GH-640: Add test for wgs endpoint

- deploy/gotc-dev/terraform/broad-gotc-dev-provider.tf
- deploy/gotc-dev/terraform/dns.tf
- deploy/gotc-dev/terraform/global_vars.tf
https://broadinstitute.atlassian.net/jira/software/projects/GH/boards/530?selectedIssue=GH-707
Add terraform config to create a public IP address and DNS record for the WFL UI.
Note: This uses the same shared terraform state file as the auth proxies for the WFL & gotc-cromwell
Thoughts on the DNS name `workflow-launcher`? The one for the API is called `wfl-auth` but that can change as well.
> [GH-707] Add DNS terraform config

- src/zero/module/xx.clj
We need to be using the correct `target_interval_list`, `bait_interval_list`, and `reference_fasta`. Not using the correct files can mess up the metrics and cause incorrect values to be calculated.
Additionally, the `cram_ref_fasta` changes based on what we're reprocessing.
Corrected the `target_intervals`, `bait_intervals`, and `cram_ref_fasta`.
> Use correct targets, baits, and fasta

- .github/workflows/docker_build_and_publish.yml
- src/zero/boot.clj
- src/zero/zero.clj
This PR is to create a gitaction that will build and publish the wdfl api and wfl ui docker images
Since deployment keys are unique, and we required all three repos involved to have a deployment key, a change had to be made to the clojure code which generates the URLs that are used to clone repos. This is now wrapped in a try/catch statement, which will first try the aliased URLs and then try the non-aliased URLs. We could have alternatively altered the code to allow the wfl repo to be cloned via the https URL and then use the SSH URL for the remaining repos, but that was a more involved change than this and so was considered less of an ideal solution.
Verify that the workflow succeeds and a new image is pushed to the location in dockerhub:
broadinstitute/workflow-launcher-api …
> Ra master docker build n publish

- .github/workflows/docker_build_and_publish.yml
- Our branch naming conventions are conflicting with the docker tag constraints.
- No changes.
> Docker build only on pushes to master branch

- ui/package-lock.json
- ui/package.json
- ui/public/index.html
- ui/src/App.vue
- ui/src/components/TopBar.vue
- ui/src/router/index.js
- ui/src/store/index.js
- ui/src/store/modules/auth.js
- ui/src/views/Login.vue
Addresses: https://broadinstitute.atlassian.net/browse/GH-742
Users who are not logged in are redirected to this login page:
After signing in, users are redirected to the dashboard page. They will also be able to see the icon to toggle the sidebar and a logout button in the navigation bar:
- Note: The API requests that require authentication will return 401 errors until the change to the WFL server goes in.
> [GH-742] Update login UI

- ui/src/store/modules/auth.js
Fix an error with the UI sending authenticated requests in the deployed WFL: `www-authenticate: Bearer error="invalid_request", error_description="No bearer token found in the request"`
Set the "Authorization" headers for the auth proxy instead of "authentication" 🤔 
> Update auth headers

- ui/src/App.vue
- ui/src/components/TopBar.vue
- ui/src/router/index.js
- ui/src/views/Error.vue
Fixes for https://broadinstitute.atlassian.net/browse/GH-742
- If you click "logout" when the sidebar is toggled open, it should now close (previously it stayed open)
- If you get a 401 error, you will now see an error message:
Note the new error page is hard-coded and very bare-bones at the moment, but we can iterate on this later to handle other possible errors!
> [GH-742] Additional UI fixes

- ui/src/App.vue
The previous PR for fixes contained an error that prevented the redirect to the error page. Now if you get a 401 error in the WFL UI, it should redirect you to a page that says "Access Denied"  
- No changes.
> [GH-742] Fix showing error message

- src/zero/wdl.clj
WFL should not attempt to delete _ALL_ files in a users `java.io.tmpdir` directory. This directory is shared with many other applications, and wiping out all files here can be detrimental for users. If the user has a lot of tmp files, then WFL will appear to hang while `util/delete-tree` recursively deletes every file. Additionally, it can create problems for other applications that put their tmp files in this directory.
Made WFL create a new temporary directory for its WDL hackery instead of using a shared tmp directory and deleting everything in it.
> Create new temp directory for WDL hackery

- deps.edn
- tests.edn
Use the same test runner for unittests and integration tests. There's no need to use two separate ones.
1. Replace test runner in deps.edn
2. Add `unittest` identifier to tests.edn
Unit tests can still be run in the usual way:
````
clojure -A:test
````
Should the integration and unit tests be combined under a common alias for convenience? I wonder if something like this is more useful:
````
clojure -A:test             # run all tests in wfl
clojure -A:unittest       # run all unit tests 
clojure -A:integration  # run all integration tests 
````
> use one test runner for wfl

- src/zero/api/handlers.clj
- src/zero/api/routes.clj
The newer `/api/v1/workload` endpoint has the same purpose.
Remove the `api/v1/workloads` endpoint
> Remove old "workloads" endpoint

- src/zero/service/pubsub.clj
- test/zero/unit/pubsub_test.clj
Test that a pubsub message is added to a topic when a file is uploaded to a GCS bucket configured to use pubsub notifications.
- Add an acknowledge function to the pubsub module
- Add a test to `pubsub_test.clj` for GH-782
> [GH-782] Test pubsub notifications for GCS

- deps.edn
- src/zero/api/handlers.clj
- src/zero/api/routes.clj
- src/zero/boot.clj
- src/zero/dx.clj
- src/zero/main.clj
- src/zero/metadata.clj
- src/zero/module/all.clj
- src/zero/module/copyfile.clj
- src/zero/module/ukb.clj
- src/zero/module/wgs.clj
- src/zero/module/wl.clj
- src/zero/module/xx.clj
- src/zero/once.clj
- src/zero/server.clj
- src/zero/service/cromwell.clj
- src/zero/service/datarepo.clj
- src/zero/service/gcs.clj
- src/zero/service/postgres.clj
- src/zero/service/pubsub.clj
- src/zero/util.clj
- src/zero/wdl.clj
- test/zero/integration/v1_endpoint_test.clj
- test/zero/tools/endpoints.clj
- test/zero/tools/fixtures.clj
- test/zero/unit/all_modules_test.clj
- test/zero/unit/datarepo_test.clj
- test/zero/unit/pubsub_test.clj
We should use the same linting tool for both WFL and the PTC service. 
- Use `cljfmt` instead of `eastwood`. Cljfmt includes auto-formatting which should make it trivial to fix any linting errors.
> Use cljfmt for linting

- ops/cli.py
The logging in CLI doesn't match the state of the program. For example, we can log "success" when the command actually failed because success is printed before that command is evaluated.
Aim of this change is to tidy-up this behaviour. I also took the liberty of
- grouping together functions that are called in succession (e.g. `print` and `dye_message_with_color`).
- ensuring defaults are defined in one place
- removing unnecessary static methods
> only print success when the command succeeded + tidy-ups

- docs/md/README.md
(Cursive's docs online only apply to slightly older versions
of IntelliJ and this project has an extra step of needing to
use `boot` to generate the `project.clj` file)
IntelliJ's old import project workflow was two steps, selecting the location and selecting how to import the project. Super recent versions of IntelliJ seem to be just inferring that last step, which makes it non-obvious that the project gets imported without using Leiningen by default.
- Update README.md to specifically state that cloning and `project.clj` generation must happen before IntelliJ import
- Update README.md to make note of selecting `project.clj` as the project to prompt a Leiningen import
- This seems to mainly apply to new installs of IntelliJ (or folks who just keep it …
> Add some notes about IntelliJ setup that weren't documented

- src/zero/api/handlers.clj
- src/zero/module/all.clj
- src/zero/module/copyfile.clj
- src/zero/module/wl.clj
- src/zero/service/postgres.clj
Address potential security vulnerabilities from concatenating user input with raw SQL statements:
https://broadinstitute.atlassian.net/jira/software/projects/GH/boards/530?selectedIssue=GH-761
Here are the files that currently interact with the database along with the changes I made:
- service.postgres: Modify `get-table` to check that the table exists before using that variable in a SQL query.
- api.handlers: Modify `post-start` to use a parameterized statement instead of concatenating the uuids provided by the user. 
- module.all: Modify `add-workload-table!` to use a parameterized statement when updating the workload.
- module.wfl
- module.copyfile
Any ideas what to do about this DB operation to create a new typed table? I don't think there's a way for us to use a parameterized …
> [GH-761] Use prepared SQL statements

- src/zero/boot.clj
- src/zero/util.clj
- src/zero/zero.clj
- https://broadinstitute.atlassian.net/browse/GH-807
- WFL cloned itself to put its master HEAD commit hash into `resources/zero/version.edn`. Doing so is not necessary because the current branch's HEAD commit is already in `version.edn` and is more representative of the version of the software anyway.
- Modify `util.clj` to have a function that will swallow errors, because...
- `boot.clj` no longer prints out an error message if `git diff-index --quiet` returns -1 (that exit code is the whole point of `--quiet`)
- `boot.clj` modified to exclude its own repo from what it cloned for `version.edn`
- On this branch, running `boot build` should exclude `"wfl" "<commit hash>"` from `resources/zero/version.edn`
- The testing behavior is unchanged from master (in other words, the tests run here …
> GH-807 Avoid extra WFL clones

- test/zero/integration/v1_endpoint_test.clj
Fix https://broadinstitute.atlassian.net/browse/GH-843
I wrote a bug in the `test-start-workload` test point where I got the first-unstarted workload and tried to start it.
The correct behaviour should be to always create the workload before starting it.
Always create a new workload before starting it. Note this is still failing due to https://broadinstitute.atlassian.net/browse/GH-845
> always create a new workload before starting it

- src/zero/module/all.clj
- Fixes https://broadinstitute.atlassian.net/browse/GH-845. It seems the prepared statement should not have single quotes, otherwise they will be kept and escaped by the clever jdbc lib.
- Removed the redundant single quotes for prepared statement.
> Fix the redundant single quotes for prepared statement.

- ops/cli.py
- https://broadinstitute.atlassian.net/browse/GH-844
- We'd like cli.py to be able to deploy to more places
- Update the comment at the top of the file (update requirements, remove out-of-date example in favor of folks looking at help text)
- Add a bunch of arguments offering granular control over the deployment project, gotc folder, cluster, and zone. Examples below.
- Add console output to indicate what the deployment config got worked out to based on arguments
- Add --dry-run to just show the deployment config and exit
(Existing behavior) gotc-dev:
```
python3 ops/cli.py deploy -d
=> Deploy config:
GCP project: broad-gotc-dev
GCP zone: us-central1-a
GCP cluster: gotc-dev-shared-us-central1-a (namespace: default)
GOTC deploy folder: gotc-deploy/deploy/gotc-dev
=> Exiting due to …
```
> [GH-844] Deploy script parameterization

- ops/cli.py
Patch cli.py - argument name rename not propagated.
propagate argument name change
name `cloudsql` consistently
> fix argument rename. name 'cloudsql' consistently.

- deps.edn
- src/zero/boot.clj
- https://broadinstitute.atlassian.net/browse/GH-859
- We don't like errant warning messages and setting this option removes one.
- Set the jar to multi-release so Log4j2 is happier and doesn't print a warning
- `boot build` followed by `java -jar target/wfl*.jar -h` will no longer print a warning message
complaining about a reflection issue.
> [GH-859] Set jar to multi-release to remove a warning message

- src/zero/main.clj
`info` level logging to `zero.main` broke deployment as the deployment script, `cli.py` reads the stdout of
```bash
$ java -jar target/wfl-*.jar version-json | jq .version
```
Logging in this case made the version-json entry-point no longer print valid json. 
Remove info logging in `zero.main/-main`
> remove ino logging in -main as this breaks parsing version-json

- src/zero/jdbc.clj
- https://broadinstitute.atlassian.net/browse/GH-860
- Bind values within macro and re-return it after side-effect.
With:
```clojure
(macroexpand `(jdbc/with-db-transaction [tx (postgres/zero-db-config)]
(jdbc/query tx ["SELECT uuid FROM workload"])))
```
The changes are more obvious:
```clojure
(let*
[id__12689__auto__ (clojure.core/rand-int 10000)]
(clojure.tools.logging.readable/info
"JDBC SQL transaction"
id__12689__auto__
"started to"
(zero.jdbc/clean-db (zero.service.postgres/zero-db-config)))
(clojure.java.jdbc/with-db-transaction
[zero.api.handlers/tx (zero.service.postgres/zero-db-config)]
(zero.jdbc/query zero.api.handlers/tx ["SELECT uuid FROM workload"]))
(clojure.tools.logging.readable/info "JDBC SQL transaction" id__12689__auto__ "ended"))
```
```clojure
(let* …
```
> [GH-860] Fix the nil return issue with db transaction context macro

- ops/cli.py
Liquibase changed their base image and have broken @rexwangcc's fix.
Small pr to address this.
Undo liquibas workaround: https://github.com/broadinstitute/wfl/pull/71/files#diff-da2a4da0fe1bbdf1dbae6823c2a89d66R175
Ensure you're not using any cached docker images.
> fix deployment after liquibase updated their base image

- cloud_function/deploy.sh
- Change the service account that the cloud function uses in the broad-gotc-dev project 
- Support deploying to the broad-aou project (the _WFL_URL is intentionally left blank here because that WFL instance hasn't been deployed yet).
See above :) 
> [GH-856] Update cloud fn deploy script

- cloud_function/tests/upload_test_files.py
- deps.edn
- src/zero/api/handlers.clj
- src/zero/api/routes.clj
- src/zero/api/spec.clj
- src/zero/module/aou.clj
- test/zero/integration/v1_endpoint_test.clj
- tests.edn
- Upgrade the version of Arrays pipeline to `v1.9.1`. (see https://broadinstitute.slack.com/archives/CESEYJW9W/p1596465923385200)
- Use tempdir to avoid polluting file system when running cloud function tests locally. 
- Refactor the specs so they are grouped in a reasonable way for future development.
- Remove a wgs workflow test from the endpoint testing, remove that endpoint as well.
- Switch to use the `documentation` reporter as the default progress of kaocha. 
Before:
```
unit:   100% [==================================================] 13/13
13 tests, 60 assertions, 0 failures.
```
After:
```
--- integration (clojure.test) ---------------------------
zero.integration.v1-endpoint-test
test-exec-wgs-workload
The `exec` endpoint creates and starts a …
```
> Miscellaneous fixes and improvements for WFL

- cloud_function/deploy.sh
Cloud functions triggered off of bucket events need to be deployed in the same project as the bucket.
Update this script to deploy to `broad-aou-storage`, where the input/trigger bucket is located.
> [GH-852] Change AOU deployment project

- .github/workflows/docker_build_and_publish.yml
- Makefile
Now that `wfl` uses semantic versioning, we should disable this automation as it'll clobber the images in docker hub.
We should instead adopt a release workflow and bump versions accordingly. 
Make the `Build and Publish Docker` manually initiated.
> disable workflow on push into master - make manual

- cloud_function/main.py
- cloud_function/tests/unit_tests.py
Fixes https://broadinstitute.atlassian.net/browse/GH-883
Update the file path structure that the cloud function uses to find a sample's `ptc.json` file.
> [GH-833] Fix parsing file paths in AOU cloud function

- ops/cli.py
- ops/render_ctmpl.py
- ops/util/misc.py
- https://broadinstitute.atlassian.net/browse/GH-877
- Supersedes #87 
- New usage:
```
usage: cli.py [-h] [-d] COMMAND ENV INSTANCE [...]
deploy or connect to WFL infrastructure
positional arguments:
COMMAND               one of [info, connect, deploy]
ENV                   specify 'gotc-deploy/deploy/{ENV}' with one of [gotc-
dev, gotc-prod, aou]
INSTANCE              specify the ID of the instance to use in the
environment
optional arguments:
-h, --help            show this help message and exit
-d, --dry-run         exit before COMMAND makes any remote changes
-v VERSION, --version VERSION
specify the version to use instead of the 'version'
file
--project PROJECT     specify the GCP project name instead of 'broad-{ENV}'
--cloud-sql-name CLOUD_SQL_NAME
specify the Cloud SQL name …
```
> [GH-877] New cli.py for new wfl-instance Terraform module

- ops/cli.py
- ops/render_ctmpl.py
- https://broadinstitute.atlassian.net/browse/GH-797
- A result of https://broadinstitute.atlassian.net/browse/GH-877
- The deploy script just needs a smidge more parameterization internally to let values files be flexible enough for sandboxes
- Interpolate the helm installation name
- Supply the instance id to the template so the template can do more interpolation if it needs
- Also allow the render script to actually supply things to the template
- From the root of WFL's directory you can run the following to see that the render function works with the custom arguments:
```
./ops/render_ctmpl.py derived/2p/gotc-deploy/deploy/gotc-dev/helm/wfl-values.yaml.ctmpl -e WFL_DB_URL=foo
```
foo will appear in the rendered file
- The deploy stuff will be tested by me deploying to gotc-dev and aou …
> [GH-797] Sandbox parameterization

- api/build.boot
- api/deps.edn
- api/module.mk
- api/src/zero/boot.clj
- api/tests.edn
- makerules/Makefile.module
- ops/server.sh
I misconfigured boot to not treat the generated `environments.clj` as a source.
I've moved the generated source into a "derived sources" directory and changed project configuration accordingly.
Bonus fixes:
prebuild when boot.build changes
check when deps.edn changes
Testing:
Verified that the jar now contains the environments. From the wfl directory:
```bash
$ clojure -Scp derived/api/target/wfl.jar`
user=> (load "zero/environments")
user=> zero.environments/aou-prod
{:cromwell {:job-mgr nil, :labels [:data_type :project :regulatory_designation :sample_name :version], :monitoring_script nil, :url 
[SNIP]
```
We still have all the resources too:
```bash
$ java -cp derived/api/target/wfl.jar zero.main version-json
{"ExternalExomeReprocessing.wdl":"ExternalExomeReprocessing_v1.1", …
```
> Use generated environments in JAR

- api/src/zero/dx.clj
- api/src/zero/main.clj
The behaviour of `dx` was different to what was documented in README. Specifically, it contained a lot of logging information.
Logging in `zero/main` make the command line usage of `wfl` noisy. In server mode, logging makes a lot of sense but not as a console application.
Remove logging from the `zero.main/main` and `zero.dx` namespaces to restore old behaviour.
> remove logging from zero.main and dx

- cloud_function/tests/upload_test_files.py
- In pursuit of QA'ing [GH-868](https://broadinstitute.atlassian.net/browse/GH-868) Saman and I discovered some issues with linking everything together in the `broad-aou` project. Most of the changes were made in gotc-deploy but this one is needed to have the test upload actually reference the right cromwell and environment
- Adds a `-p`/`--prod` flag so you can use `python3 upload_test_files.py -b broad-aou-arrays-input --prod` to kick off the cloud function in the aou environment
- You can run `python3 upload_test_files.py -b broad-aou-arrays-input --prod` and see that the cloud function logs show that cromwell started
> Cloud function test upload able to target prod

- api/src/zero/module/all.clj
- api/src/zero/module/aou.clj
- api/test/zero/tools/workloads.clj
- cloud_function/deploy.sh
- cloud_function/main.py
Use the cromwell workflow option to copy outputs (ticket https://broadinstitute.atlassian.net/browse/GH-887)
- Use the `output` defined in the create/exec workload payload instead of the placeholder string and fail if it is not a valid gs-url
- When creating a workload, check the output in addition to the pipeline, project & release (so changing the output location will result in creating a new workload)
- When appending workflows, construct the final workflow outputs path by appending "/chip-well-barcode/analysis-version-number" to the workload `output`
- Cromwell options specify the final output directory & uses the relative output paths
> [GH-887] Add AoU final workflow outputs directory

- .gitignore
- api/src/zero/api/routes.clj
- api/src/zero/api/spec.clj
- https://broadinstitute.atlassian.net/browse/GH-841
- Fix a mis-configured spec for `/workload`.
- Add partial support for Swagger OAuth2. 
**Note:**
The OAuth support for Swagger is not fully-functional. I haven't found a decent way to make it work. We might want to keep an eye on how the `reitit` folks respond to https://github.com/metosin/reitit/issues/430
> [GH-841] Fix some endpoint specs and add Swagger OAuth2 button

- makerules/common.mk
When tests fail, we want `make` to report these failures and fail itself.
I'm `tee`ing test results into a log file because if i parallel build, I have a coherent record of the test failure (rather than fragments strewn about the place)
The solution is to fix the shell on 'nix platforms to `bash` and use the pipefail option. See the following links for more info:
https://stackoverflow.com/questions/25306774/best-way-to-handle-pipes-and-their-exit-status-in-a-makefile
https://unix.stackexchange.com/questions/14270/get-exit-status-of-process-thats-piped-to-another/73180#73180
> [GH-910] use `bash` as `make`s shell. set pipefail

- makerules/common.mk
- ui/module.mk
The first issue is that MacOS by default ships with an older version of `gmake` that doesn't support `.SHELLFLAGS`
The second issue was that BSD dirname only accepts one file, rather than many. I didn't need to shell out to get the list of uinique dirnames so I'm using build-in Make functions instead.
> [GH-910] GMake failures on Mac

- cloud_function/README.md
- cloud_function/dev-requirements.txt
- cloud_function/module.mk
- cloud_function/pytest.ini
`make cloud_function TARGET=check` currently fails as the environment is misconfigured.
This is a symptom of a larger problem in that to run the tests, we have to manually set the environment.
[pytest-env](https://github.com/MobileDynasty/pytest-env) is a nice little plugin that reads the environment variables out of `pytest.ini`. I propose we use this to manage and configure the environment.
This PR fixes GH-911.
related SO article:
https://stackoverflow.com/questions/36141024/how-to-pass-environment-variables-to-pytest
> [GH-911] configure pytest environment with `pytest-env` plugin

- cloud_function/main.py
The cloud function SA does not have access to the cloud chip metadata directory containing the extended chip manifest file.
Make the cloud function only check for files that PTC uploads. If the extended chip manifest file isn't there (which is not likely to happen) the cromwell workflow would still fail.
> [GH-936] Make cloudfn only check files uploaded by PTC

- .github/workflows/release_latest_version.yml
- https://broadinstitute.atlassian.net/browse/GH-914
- Locks Python version to what works for me locally. This will solve the issue of the default Python being too old to use `dataclass`
- Use pip to install pyyaml, a dependency I haven't thought about in a while but that I suppose we'll need here
- Competing information online about if we need to do configuration to Git, but I'd rather just play it safe. Git user and email inferred from the commit.
- Wait for a new release, I suppose.
- I wish I had set up better tooling to test this, I'm sorry that getting this working has been so rocky. Since our releases and tags actually have meaning even if I were to do this locally I would still have to wait for real releases.
> [GH-914] Add Python and Git configurations

- api/src/wfl/api/handlers.clj
- api/src/wfl/api/spec.clj
- api/src/wfl/service/gcs.clj
- api/test/wfl/tools/workloads.clj
- api/test/wfl/unit/gcs_test.clj
- cloud_function/main.py
- ops/server.sh
https://broadinstitute.atlassian.net/browse/GH-954
Interestingly, the keys in the header map are lower case, hence I'm checking for Authorization as well as authorization. Not sure whats cauing this... Ideas welcome.
Remove `creator` as a field from the `workload-request`
Get this information from the `userinfo` gcs oauth api.
Added automated test.
@samanehsan  Is this change going to cause problems for the cloud function?
> [GH-953] get creator from auth token instead of via the workload-request

- ops/server.sh
The issue is in setting suspend=y- this makes the jvm wait until you attach a debugger.
> [GH-964] don't suspend jvm on entry

- api/test/wfl/integration/v1_endpoint_test.clj
- api/test/wfl/tools/endpoints.clj
- api/test/wfl/tools/workloads.clj
Fixes: https://broadinstitute.atlassian.net/browse/GH-948
- Make the WGS test workload output directory different for each test run. Otherwise WFL will not start the workload because there's an output already in that directory.
- Make the integrations tests use the api server when running locally
> [GH-948] Fix "output already exists" error in WGS tests

- api/build.boot
- api/deps.edn
- api/src/wfl/service/postgres.clj
- docs/md/dev-process.md
- ops/cli.py
- https://broadinstitute.atlassian.net/browse/GH-950
- Added a new alias `clojure -A:liquibase` to `deps.edn` so it's much easier to run local liquibase migrations. **FULL CREDIT to @tbl3rd**
- It is unexpectedly tricky to add a command to `cli.py` for this. I ran into a similar issue to https://github.com/liquibase/docker/issues/11 that 
```
docker run --rm --net=host -v /path/to/database:/liquibase/changelog liquibase/liquibase --url='jdbc:postgresql://localhost:5432/wfl?useSSL=false' --changeLogFile=/changelog/changelog.xml --username='$USER' --password='None' update` just cannot work and always raise 
```
`Connection could not be created` exceptions. That code is still committed but I plan to revert it since it does not work.
- Try run `clojure -A:liquibase` from within `api/`
> [GH-950] Easier local liquibase migration

- api/src/wfl/service/gcs.clj
- api/test/wfl/tools/fixtures.clj
- api/test/wfl/tools/workloads.clj
- api/test/wfl/unit/datarepo_test.clj
- api/test/wfl/unit/gcs_test.clj
- cloud_function/tests/upload_test_files.py
Ticket: https://broadinstitute.atlassian.net/browse/GH-949
- Make `with-temporary-gcs-folder` use the new test output bucket `broad-gotc-dev-wfl-ptc-test-outputs` that has an object lifecycle policy of 1 day
- Make the gcs-object test use `with-temporary-gcs-folder` instead of creating new buckets
- Make the data-repo test use `with-temporary-gcs-folder`instead of creating a new bucket
- Remove `bucket-test` for creating, listing & deleting buckets
- Remove gcs `make-bucket` and `delete-bucket` since they are no longer used after these changes (they were previously only used by the tests)
- Updated WGS and AOU test workloads inputs to use `broad-gotc-dev-wfl-ptc-test-inputs`
- Updated cloud function helper script to use AOU test inputs from `broad-gotc-dev-wfl-ptc-test-inputs`
The …
> [GH-949] Consolidate test buckets

- api/test/wfl/integration/v1_endpoint_test.clj
- api/test/wfl/system/module_test.clj
- api/tests.edn
Before automating integration tests to run on PRs, move the time-consuming tests into a separate system test alias. 
Ticket: https://broadinstitute.atlassian.net/browse/GH-987
Move every test that waits for a Cromwell workflow to complete under a new system test alias.
Notes: 
- The append to AoU test succeeds before the workflow actually finishes (looks like a bug) so even though it currently completes very quickly I'm not sure if it would once we fix it (created a ticket for this here: https://broadinstitute.atlassian.net/browse/GH-995)
- The WGS create test waits for a Cromwell workflow to succeed, but it actually completes very quickly due to call-caching so I wasn't sure where to put that one.
> [GH-987] Split system and integration tests

- api/test/wfl/integration/datarepo_test.clj
- api/tests.edn
- https://broadinstitute.atlassian.net/browse/GH-982
- Move datarepo test to integration and mark it as pending
- Run `clojure -A:test unit` and make sure `datarepo` test is not run anymore.
> [GH-982] Move datarepo test to integration and mark it as pending

- ops/cli.py
Ticket: https://broadinstitute.atlassian.net/browse/GH-1000
- Use `.get` syntax when getting `ZERO_POSTGRES_USERNAME` & `ZERO_POSTGRES_PASSWORD ` from the rendered values file in case it's not specified.
- Error out if there is no `config.db_username` or `config.db_password` 
> [GH-1000] Fix cli deploy script

- .github/workflows/release_latest_version.yml
Seems like #162 didn't stick and the `make` system builds WFL multiple times, thus ignoring the `USER=` set during initial building. I suppose that makes sense with how long the release job takes.
This should properly accomplish what I intended in #162, see that PR for more information
> Make author on dashboard more clear, again

- .github/workflows/pr-test.yml
- api/module.mk
- api/src/wfl/boot.clj
- api/src/wfl/module/wgs.clj
- docs/md/README.md
- https://broadinstitute.atlassian.net/browse/GH-983
- Let WFL clone WARP and switch the wgs module over to use warp.
- This PR introduces a somewhat duplicated function `cromwellify-warp-wdl` in `boot.clj` in order to support both `dsde-pipelines` and `warp` at the same time.
- This PR updates the Github Actions `pr-test` so it builds without errors.
- This PR updates `wgs.clj` to use `ExternalWholeGenomeReprocessing_v1.1.0` rather than `ExternalWholeGenomeReprocessing_v1.0` since `Warp` does not have the latter tag. This requires PR #157 to resolve merge conflicts later.  
- `make distclean` and `make api TARGET=check` should pass.
> [GH-983] Let WFL clone WARP and switch the wgs module over to use warp.

- api/test/wfl/integration/datarepo_test.clj
- https://broadinstitute.atlassian.net/browse/GH-997
- Remove the `^:exclude` that, well, excluded the test
- It is still a integration test so it won't run on PR
> [GH-997] Re-enable data repo test

- api/src/wfl/boot.clj
- api/src/wfl/module/aou.clj
This reverts commit fdefbf9c66248be5b53598ab12e6da6ea9e6659c.
Arrays_v2.0 in WARP is unusable and I don't know what to do about it, we just need to revert WFL to not use WARP for AoU ASAP.
dsde-pipeline's InternalArraysTasks.wdl#L148 @ Arrays_v2.0:
```
'NR==1{for(i=1;i<=NF;i++){if($i==col){c=i;break}}} NR==2{print $c}  NR>2{exit 1}')
```
WARP's InternalArraysTasks.wdl#L148 @ Arrays_v2.0:
```
'NR==1{for(i=1;i<=NF;i++){if($i==col){c=i;break}}} NR==2{print $c} NR>2{exit 1}'')
```
(Notice the extra `'`, which causes an EOF error when Cromwell tries to parse it)
> Revert "[GH-985] Use WARP for AoU (#167)"

- api/src/wfl/api/spec.clj
- api/src/wfl/module/wgs.clj
Ticket: https://broadinstitute.atlassian.net/browse/GH-1007
Use the `base_file_name`, `final_gvcf_base_name` or `sample_name` if they are specified in the workload, otherwise use the default input cram name.
Should "sample_name" actually be an optional field?
> [GH-1007] Check WGS workload values before using defaults

- api/src/wfl/api/routes.clj
- https://broadinstitute.atlassian.net/browse/GH-1026
- Makes the `/oauth2id` endpoint lazier so that it won't try to come up with its response during `prebuild`
- You can run a local server to see that the endpoint still works
- Tests here should still pass
- There should be no error text in the output of the `prebuild` step of the github action here
> [GH-1026] Make the `/oauth2id` endpoint lazier

- api/test/wfl/system/v1_endpoint_test.clj
- api/test/wfl/tools/endpoints.clj
- api/test/wfl/tools/workloads.clj
I made a silly mistakes in using one of the endpoint test tools. 
I've changed the code such that:
- `endpoints/append-to-aou-workload` takes a list of samples and the workload to append to
- `workloads/when-done` takes the workload as the last argument for better chaining support. It calls `done!` with the updated workload.
> [GH-1019] Fix append-to-aou-workoad test

- api/src/wfl/boot.clj
- api/test/wfl/unit/all_modules_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1031
- Add the WARP WDLs back into what ends up in the version file
- Add a fast-running unit test that WDL versions are in the version.edn
The PR will run the unit test showing that the version.edn file contains the versions of the WDLs, and since the code that produces "Unknown" is
```clojure
(key-for :wdl-version) (or (the-version wdl-value) "Unknown")
```
we should be all set. Can also verify via logging in to `./ops/server.sh`, you'll see the WARP WDL version info on the right-hand side again which is just read straight out of `version.edn`.
> [GH-1031] Fix unknown pipeline version

- api/src/wfl/api/spec.clj
- api/test/wfl/system/v1_endpoint_test.clj
Fixes GH-1032:
In spec, accept one or more samples.
Add test points to `test-append-to-aou-workload` to lock down behaviour.
> [GH-1032] append-to-aou accepts one or more sample

- api/src/wfl/references.clj
- api/test/wfl/unit/references_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1034
- Make `hg38-genome-references` smarter about not passing nil to `reference_fasta`
- Can't use fnil because the default is in the function
- Add a test for prefix handling in the references file
- See the ticket for more info on what happened here
> [GH-1034] Fix reference_fasta function

- api/test/wfl/tools/workloads.clj
- cloud_function/main.py
- cloud_function/module.mk
Change cloud_function after https://github.com/broadinstitute/wfl/pull/196
- remove unused endpoint message fields
- make the tests run
> update cloud_function after api tidy-ups

- api/src/wfl/service/terra.clj
- api/src/wfl/util.clj
- api/test/wfl/integration/terra_test.clj
Started as a part of https://broadinstitute.atlassian.net/browse/GH-1018
- Adds a terra module with functions to: 
- Create a submission
- Get a submission by uuid
A submission is like Terra's concept of a workload. It includes what data need to get processed with what pipeline and when you make a request to get a submission it includes a list of the workflows that were started in Cromwell.
> [GH-1035] Add terra module to WFL

- api/test/wfl/integration/modules/aou_test.clj
- api/test/wfl/integration/modules/wgs_test.clj
- api/test/wfl/integration/modules/xx_test.clj
- api/test/wfl/system/v1_endpoint_test.clj
- api/test/wfl/tools/fixtures.clj
- api/test/wfl/tools/workloads.clj
By popular demand, use a random db name in tests. This means that you no longer need to remove the `wfl` database before running integration tests.
> use random db name in tests

- api/src/wfl/module/batch.clj
- api/src/wfl/module/xx.clj
- database/changelog.xml
- database/changesets/20201029_BatchWorkflow.xml
- database/changesets/20201029_CromwellWorkflow.xml
- database/changesets/20201030_ExternalExomeReprocessing.xml
The table I wrote for external exome reprocessing is actually generic across the set of batch workloads in cromwell.
I intend to re-use this when extending the WGS module.
Note that the database changes are breaking. Since the exomes module is not released yet, however, I don't think this is an issue.
I could have unified the all/create-workload-table and the batch version but decided against otherwise it would have caused a lot of merge conflicts for jack. I'll tidy this up later.
> [GH-1022] Repurpose external exome table for batch workloads

- api/src/wfl/api/handlers.clj
- api/src/wfl/api/routes.clj
- api/src/wfl/api/spec.clj
- api/test/wfl/tools/endpoints.clj
- docs/md/dev-wgs.md
- docs/md/external-exome-reprocessing.md
- docs/md/modules-arrays.md
- https://broadinstitute.atlassian.net/browse/GH-1024
- Discussions:
- https://github.com/broadinstitute/wfl/pull/164#discussion_r501691419
- https://broadinstitute.slack.com/archives/CFA6Q2QBU/p1603916497140900
Now you could run something like:
```bash
curl -X "POST" "http://localhost:3000/api/v1/start" \
-H 'Authorization: Bearer $(gcloud auth print-access-token)' \
-H 'Content-Type: application/json' \
-d $'{
"uuid": "d0ab1865-556e-4a7e-8f5c-de80d1081529",
}'
```
to start a single workload, and the response will also be a single map that represents a workload entity. The easiest way to test is to call `create` and `start` sequentially:
```bash
curl -X "POST" "http://localhost:3000/api/v1/create" \
-H 'Authorization: Bearer $(gcloud auth print-access-token)' \
-H 'Content-Type: …
```
> [GH-1024] Make start workload endpoint take a single UUID

- .github/workflows/release_latest_version.yml
The purpose of this change is so that we can store in `version` the version of the next release.
This enables backwards compatibility testing where previously, it was impossible to know if the code had already been released was released or not (i.e. `version` contained the last released version)
I've switched the github action to use a manual trigger.
> disable automatic release action

- api/test/wfl/integration/datarepo_test.clj
- api/tests.edn
Really this could be automated... Disable failing test until https://broadinstitute.atlassian.net/browse/GH-1048 is complete
> [GH-1050] disable `wfl.integration.datarepo-test/delivery`

- api/src/wfl/module/aou.clj
- api/src/wfl/util.clj
Ticket: https://broadinstitute.atlassian.net/browse/GH-1044
Set the `maxRetries` workflow option to 1 by default to automatically retry transient failures in Cromwell: https://cromwell.readthedocs.io/en/stable/RuntimeAttributes/#maxretries. 
This includes the `aou`, `wgs`, `xx` and `copyfile` modules.
> [GH-1044] Set default maxRetries workflow option

- api/src/wfl/module/wgs.clj
- api/src/wfl/module/xx.clj
- api/test/wfl/integration/modules/wgs_test.clj
- docs/md/external-exome-reprocessing.md
Using the reference_fasta_prefix to dictate all the references is weird. We should only use it to compute the reference_fasta.
- merge the reference_fasta into references if the specifies them
- don't make default values part of the API. This makes back-porting fixes + updated input values easier.
> [GH-1061] don't send back defaults when user specifies reference_fasta_prefix

- api/src/wfl/api/handlers.clj
- api/src/wfl/api/routes.clj
- api/src/wfl/api/spec.clj
- api/src/wfl/api/workloads.clj
- api/src/wfl/util.clj
- api/test/wfl/integration/modules/copyfile_test.clj
- api/test/wfl/integration/workloads_test.clj
- api/test/wfl/tools/workloads.clj
- api/test/wfl/unit/spec_test.clj
- docs/md/dev-wgs.md
- docs/md/external-exome-reprocessing.md
- docs/md/modules-arrays.md
- https://broadinstitute.atlassian.net/browse/GH-1023
Create a workload and query for it by project:
```
curl -X "POST" "http://localhost:3000/api/v1/create" \
-H "Authorization: Bearer $(gcloud auth print-access-token)" \
-H 'Content-Type: application/json' \
-d $'{
"cromwell": "https://cromwell-gotc-auth.gotc-dev.broadinstitute.org",
"project": "(Test) WFL Local Testing",
"input": "fake-input",
"items": [
{
"inputs": {
"dst": "gs://broad-gotc-dev-zero-test/wfl-test-b17d834c-7c27-4e7a-a6df-3e2a4ef4def7/output.txt",
"src": "gs://broad-gotc-dev-zero-test/wfl-test-b17d834c-7c27-4e7a-a6df-3e2a4ef4def7/input.txt"
}
}
],
"output": "fake-output",
"pipeline": "copyfile"
}'
```
then
```
curl "http://localhost:3000/api/v1/workload?project=(Test)%20WFL%20Local%20Testing" \
-H "Authorization: Bearer …
```
> [GH-1023] Support querying workloads by project name

- api/src/wfl/api/handlers.clj
- api/test/wfl/integration/modules/wgs_test.clj
- api/test/wfl/system/v1_endpoint_test.clj
- api/test/wfl/unit/api_handlers_test.clj
- api/test/wfl/unit/workloads_test.clj
During the hOps demo, it became clear that the `:id` property of a workload (and it's workflows) caused confusion. In this change, I propose to purge this property from the workload responses.
The `:items` table in workloads is an internal detail and we should not be sending that back either.
> [GH-1063] Remove Serialisation Internals from Workload Responses

- api/src/wfl/module/copyfile.clj
- api/src/wfl/module/wgs.clj
- api/src/wfl/module/xx.clj
- api/test/wfl/integration/modules/copyfile_test.clj
- api/test/wfl/integration/modules/wgs_test.clj
- api/test/wfl/integration/modules/xx_test.clj
This fixes the difference in behaviour for when a user specified `nil` as the workflow `options` or `{}`.
Now, the options are returned if they're not empty or nil.
Example: 
```bash
curl -X POST 'https://dev-wfl.gotc-dev.broadinstitute.org/api/v1/create' \
-H 'Authorization: Bearer '$(gcloud auth print-access-token) \
-H 'Content-Type: application/json' -d '{ 
"cromwell": "https://cromwell-gotc-auth.gotc-dev.broadinstitute.org",
"output": "gs://broad-gotc-dev-wfl-ptc-test-outputs/wgs-test-output/",
"pipeline": "ExternalWholeGenomeReprocessing",
"project": "hornet bash",
"common": {
"options": {}
},
"items": [ {
"inputs": {
"input_cram": "gs://broad-gotc-dev-wfl-ptc-test-inputs/single_sample/plumbing/truth/develop/20k/NA12878_PLUMBING.cram" 
}
}
]
}'
```
now returns: 
```json
{
"creator" …
```
> [GH-1070] dont serialise empty workflow options if none are specified

- api/src/wfl/module/aou.clj
- api/test/wfl/integration/modules/aou_test.clj
- api/test/wfl/tools/workloads.clj
See ticket.
Caused by a type error. in https://github.com/broadinstitute/wfl/pull/196, I changed the implementation from `start-workload!` from
```clojure
(defmethod workloads/start-workload!
pipeline
[tx {:keys [id] :as workload}]
(do
(start-aou-workload! tx workload)
(workloads/load-workload-for-id tx id)))
```
to
```clojure
(defoverload workloads/start-workload! pipeline start-aou-workload!)
```
Without updating `start-aou-workload` to return the the workload if it had already been started.
Note that the changes to the test tools are required so that the test I added doesn't fail due to GH-1072. I think there should be a separate test added for that.
> [GH-1071] Fix `exec`-ing an AoU workload twice fails to return the `exec`-ed workload

- api/src/wfl/module/aou.clj
- api/test/wfl/integration/modules/aou_test.clj
Double submit of #236 
* Use the same slashified-output for both querying and inserting
* Add a test
* newline
* use deftest
(cherry picked from commit ea67e1469ae95e64fabaee4bf74e3fc45641ddbd)
> [GH-1072] Standardize AoU output bucket in DB (Double submit to RC branch)

- ops/cli.py
- https://broadinstitute.atlassian.net/browse/GH-1074
- Make changelog use your current branch for log calculation
- Make changelog use the raw commit text if it errors out trying to markdown-ify the PR link (this means it will work if the log includes commits that weren't made via PR)
Can verify this by Ed's original reproduction steps if you run them from this branch:
```bash
git checkout -B foo
git add foo.txt && git commit -m "add foo"
./ops/cli.py release
```
> [GH-1074] Changelog from branches

- ops/cli.py
Double-submit of #241
* make changelog from head not master
* make changelog at least able to process commits not done via PR
> [GH-1074] Double submit of Changelog from branches (#241)

- api/test/wfl/integration/datarepo_test.clj
Bug tracked in: https://broadinstitute.atlassian.net/browse/GH-1075. Does not affect product code and is not a market bug for v0.4.1 therefore.
> [GH-1076] disable `wfl.integration.datarepo-test/delivery` for v0.4.1

- CHANGELOG.md
Add change log ahead of 0.4.1 patch release
I had to manually create this due to https://broadinstitute.atlassian.net/browse/GH-1074 - I checked it and it seems ok!
> Update v0.4.1 patch release change log

- api/src/wfl/api/handlers.clj
Fixes the failing system test for the arrays module.
Import arrays module in handlers, otherwise WFL will complain that the pipeline is invalid when trying to create a new `GPArrays` workload.
> [GH-1020] Import arrays module in handlers

- ops/sam.sh
- ops/server.sh
- https://broadinstitute.atlassian.net/browse/GH-1054
- Use `#!/usr/bin/env bash` instead of `#!/bin/bash`
- Can't pass further arguments to `bash` so `-ex` becomes `set -ex`
> [GH-1054] Use portable shebangs

- api/src/wfl/module/aou.clj
- api/test/wfl/integration/modules/aou_test.clj
https://broadinstitute.atlassian.net/browse/GH-1097
As Jack observed, when you send a sample to workflow launcher that has been (or in the process of being) processed, workflow-launcher skips it. If no samples are processed, I thought I was returning an empty list. I even wrote a test for this. The problem is that Clojure treats `nil` to mean empty, meaning that the integration test I wrote wasn’t that useful.
The solution was to explicitly return the list I created, not the list returned by `jdbc/insert` - I thought they were the same, turns out not.
> [GH-1097] Fix empty append_to_aou response

- .github/workflows/pr-test.yml
In investigating https://broadinstitute.atlassian.net/browse/GH-1056, I found that caching build dependencies between jobs lead to quite a significant speed-up in PR checks (~2 mins out of 7).
While my solution for GH-1056 isn't quite there yet, this can definitely be submitted.
> Cache clojure deps between builds

- api/src/wfl/module/aou.clj
- api/test/wfl/unit/modules/aou_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1042
- If we see an `environment` in the inputs in the request, that'll now override WFL's old behavior of picking "dev" or "prod" based on the Cromwell.
- Add a unit test for exactly this.
- See PR unit tests
> [GH-1042] AoU supports custom environments

- api/src/wfl/api/spec.clj
- https://broadinstitute.atlassian.net/browse/GH-1112
- Adds `::entity-name` and `::entity-type` to the spec so it resolves properly (so the swagger.json can get generated)
- Run a local server on this branch and going to `/swagger/swagger.json` will yield the swagger JSON
> [GH-1112] Add unresolved fields to spec

- api/src/wfl/api/routes.clj
- api/src/wfl/api/workloads.clj
- api/test/wfl/system/v1_endpoint_test.clj
- api/test/wfl/unit/workloads_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1079
- Make catch/throws in `wfl.api.workloads` not clobber `ex-data` (/exec was clobbering exception types from /create or /start, etc)
- This means that the correct response codes get sent to the user
- Make server logs more concise
- Don't print that huge gob of text anymore
- If the error is 400-series, nothing gets printed
- If the error is 500-series, print out an error, request in EDN format, and stacktrace
- Make error responses to the user pure JSON (was slightly out of spec before by trying to write in a raw class object)
- Make error responses to the user pretty-printed
- Adjust system test to get some coverage on this (explanation in [commit message](https://github.com/broadinstitute/wfl/commit/beee62b265430a7dbdb2c6d484e59790966 …
> [GH-1079] Fix WFL's exception logging

- api/src/wfl/module/batch.clj
- api/src/wfl/module/wgs.clj
- api/src/wfl/module/xx.clj
- api/src/wfl/service/cromwell.clj
- api/test/wfl/integration/modules/wgs_test.clj
- api/test/wfl/integration/modules/xx_test.clj
- api/test/wfl/system/v1_endpoint_test.clj
https://broadinstitute.atlassian.net/browse/GH-1095
- Start/exec all items in a XX or WGS workload to Cromwell using the batch endpoint, instead of sending a request for each item. The batch endpoint will apply the same labels to every workflow, so item-specific labels were removed.
- Move `submit-workload!` to the batch module
- Remove WGS module skip workflow functionality
> GH-1095: Batch submit workflows to Cromwell

- functions/aou/main.py
- functions/aou/tests/unit_tests.py
https://broadinstitute.atlassian.net/browse/GH-1111
- Update how the cloud function parses the file paths, since [this change in PTC](https://github.com/broadinstitute/push-to-cloud-service/pull/61) will include an `environment` directory 
- Include the `environment` in the output directory path (this will make WFL create different workloads for staging and dev messages)
> [GH-1111] Handle Mercury staging messages for AOU

- .github/workflows/pr-test.yml
- .github/workflows/release_latest_version.yml
- https://broadinstitute.atlassian.net/browse/GH-757
- Grabs deployment keys from Vault
- The same thing is done in both deployment and the PR tests, so hopefully the test here passes
- **Question: should the dockerhub creedentials used for deployment also be replaced with ones from Vault? That's slightly higher risk**
- After merging this ticket there's a few secrets that we can safely delete, see the ticket for details
> [GH-757] Grab deployment keys from Vault, not secrets

- api/src/wfl/module/wgs.clj
- api/src/wfl/module/xx.clj
- api/src/wfl/util.clj
- api/test/wfl/unit/modules/all_test.clj
- api/test/wfl/unit/modules/xx_test.clj
- api/test/wfl/unit/utils_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1106
- Just copies the logic from WGS
- Not exactly, because there's some small behavior differences, like WGS including the unmapped bam suffix or XX not having a slash after the destination cloud path, that I thought it would be good to keep. Not wanting to make this a bigger change
- Unit tests cover this, see the test in changed files to see exactly what this change does
> [GH-1106] `final_gvcf_base_name` and `base_file_name` should be the same as the `sample_name`

- functions/aou/main.py
- functions/aou/tests/unit_tests.py
https://broadinstitute.atlassian.net/browse/GH-1111
Update the AOU cloud function to handle both the old/existing input file paths and the "new" file paths that will be prefixed with the mercury environment. This will allow us to re-deploy the cloud function without stopping PTC/having to coordinate with BITS.
> [GH-1111] Update AOU cloud fn to handle paths with or without env prefix

- api/src/wfl/main.clj
- api/src/wfl/server.clj
In this change, I'm adding the plumbing for the update loop + whatever task that needs to be done periodically. I've left the actual update function empty as I want the plumbing reviewed rather than the update code itself.
I'm using futures for the jetty server and the update loop because if either fail, I want the entire service to come down. I also wanted to tie their lifetimes somehow. Unfortunately, This means I'm using 2 extra threads. I could use the main thread to poll the status of the jetty server, but I thought that this approach was simpler for now.
What do people think of this approach? It's pretty straightforward but are there other designs people have thought about?
> [GH-1105] Add update loop plumbing

- api/src/wfl/service/postgres.clj
- api/test/wfl/integration/modules/aou_test.clj
- api/test/wfl/integration/modules/arrays_test.clj
- api/test/wfl/integration/modules/copyfile_test.clj
- api/test/wfl/integration/modules/sg_test.clj
- api/test/wfl/integration/modules/wgs_test.clj
- api/test/wfl/integration/modules/xx_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1125
- Make the SQL query for unfinished workflows also include workflows with no status, so we correctly leave such workflows untouched if we create and then call update on it
- Make all the module integration tests catch this error
- Integration tests check this via Ed's reproduction steps
> [GH-1125] Don't finish unstarted workloads

- api/src/wfl/module/aou.clj
https://broadinstitute.atlassian.net/browse/GH-1119
- Use the `vault_token_path` from the AOU inputs, since it will differ based on the mercury environment.
- Lowercase the environment variable (the WDL uses the environment input to construct a vault path, so if the environment is "Staging" instead of "staging", it will not find a value)
> [GH-1119] Get vault_token_path from AOU inputs

- api/src/wfl/api/handlers.clj
- api/test/wfl/system/v1_endpoint_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1129
- Also rename keys in /exec
- Make /create and /exec look more similar\
- Add a test to catch this
- Reproduction steps [are here](https://broadinstitute.atlassian.net/browse/GH-1129), against a local instance of this branch it'll not throw a NPE.
- This is my bad, I just didn't get how exec worked--I thought it delegated higher up the chain and it doesn't, so we have to rename the keys in both cases. I tried to make the functions a bit more similar to highlight this fact in the future, since they do actually have to do the same thing.
> [GH-1129] Avoid NPE in /exec by properly renaming keys

- ops/aou_cleanup/cleanup.py
https://broadinstitute.atlassian.net/browse/GH-1142
With the addition of the mercury environment-prefix to the AOU arrays input file paths in https://broadinstitute.atlassian.net/browse/GH-1111, the production input bucket will contain a mix of the old and new paths. Updating the old paths would require pausing PTC & deleting the cloud function (to avoid re-triggering the same samples). Instead, make the clean-up script backwards compatible so that we do not need to coordinate this with BITS and hOps.
> [GH-1142] Make aou cleanup script backwards compatible

- ops/data_repo_terra/import_snapshot_data.py
- ops/data_repo_terra/requirements.txt
Provide an example of how to get data from a snapshot in the Data Repo into a Terra workspace:
https://broadinstitute.atlassian.net/browse/GH-1144
Given a data repo snapshot, this script will:
1. Query the snapshot sample table in BigQuery
2. Save the table contents as a TSV file and return a list of the samples/entities formatted for WFL. This script uses the `datarepo_row_id` as the unique id (AKA the "entity id") of the sample in Terra.
3. Upload the TSV file to the specified Terra workspace data table
Note that the default snapshot uses the datarepo integration test dataset, since we do not have a test arrays dataset yet.
> [GH-1144] Helper script for importing Data Repo data into Terra

- .github/workflows/doc-site.yml
- .github/workflows/release_latest_version.yml
- Ed mentioned that it is weird that we don't version docs at all, I think it is a good point
- Enabled "keep_files" on our GH Pages deploy action so it doesn't delete things not replicated in the last build, because...
- ...release actions now deploy the docs into a subfolder, so https://broadinstitute.github.io/wfl/v0.5.0 or whatever
- No one would know about that link so now we add a note to the release [here](https://github.com/broadinstitute/wfl/releases)
- While we're at it, inject the most recent changelog section into those notes
- **TL;DR: current docs stay the same, but now we also get versioned docs linked to from the release for free**
- I had a touch of free time and figured I might be able to tackle this. Just an idea, not beholden to it at all
> [Snack] Version the docs

- .github/workflows/trivy.yml
As part of the initial integration of this repo into the Terra ecosystem, this change adds [Trivy](https://github.com/aquasecurity/trivy) security scan for the Docker images.
The scan will run as a GitHub Action on every PR and give you feedback if the Docker image contains Critical OS vulnerabilities. One can then either:
* fix the issue (usually just by updating the packages in the Dockerfile, or the base image itself), or
* ignore it, and document the reason with AppSec. Our compliance process has a timeline of 14 days for patching Critical vulnerabilities, or documenting why they are ignored.
As an alternative, [AppSec "blessed" base images](https://github.com/broadinstitute/dsp-appsec-blessed-images) can be used to skip over this check.
More info: …
> [GH-1145] Add AppSec Github Trivy Action

- api/test/wfl/integration/google/pubsub_test.clj
The test naively assumed that no files would be updated between the point the notification configuration was added to the bucket and when the subscription was pulled.
To fix this, we can simply swap the order of events: make sure the queue is empty and then add the notification config.
> [GH-1182] fix Pub/Sub test data race

- api/test/resources/datasets/assemble-refbased-outputs.json
Update the schema to reflect Ruchi's suggestion of partitioning by "datarepo_ingest_date"
> [GH-1176] partition by `datarepo_ingest_data` in assemble_refbased schema

- helm/wfl/Chart.yaml
The latest tag of WFL is 0.5.1. However the AppVersion was set to 0.5.0. They should be the same
Updating the AppVersion in the Chart.yaml file
Verify that this is the correct version to be on
> Updating AppVersion to the latest tag (0.5.1)

- api/resources/log4j2.xml
- api/src/wfl/environment.clj
- api/src/wfl/server.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1203
This was caused by server code reading `WFL_COOKIE_SECRET`.
Solution was to make the `cookie-store` and `app` functions
rather than a `def`ed value.
> [GH-1203]: fix reading from vault at load-time

- api/src/wfl/environment.clj
- api/src/wfl/service/cromwell.clj
- api/src/wfl/service/datarepo.clj
- api/src/wfl/service/firecloud.clj
- api/src/wfl/service/google/bigquery.clj
- api/src/wfl/util.clj
- api/test/resources/datasets/sarscov2-illumina-full-inputs.json
- api/test/resources/workflows/sarscov2_illumina_full/dataset-from-inputs.edn
- api/test/resources/workflows/sarscov2_illumina_full/entity-from-dataset.edn
- api/test/resources/workflows/sarscov2_illumina_full/flowcell-ingest-request.edn
- api/test/resources/workflows/sarscov2_illumina_full/inputs-ingest-request.edn
- api/test/wfl/integration/datarepo_test.clj
- api/test/wfl/system/automation_test.clj
- api/test/wfl/tools/datasets.clj
- api/test/wfl/tools/fixtures.clj
- api/test/wfl/tools/snapshots.clj
- api/test/wfl/unit/google/bigquery_test.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1221
In this PR, I'm adding test demonstration code for how to import data from a TDR snapshot into a Terra Workspace. This includes:
- Querying all the rows in the specified table in the snapshot
- Selecting and renaming the columns of the table to match those of the target entity
- Importing the rows as new entities into the workspace.
The renaming works by viewing the rows of the table as a list of maps, mapping those names onto workspace names, then reconstructing the table.
Added dataset/snapshot querying utilities to the `datarepo` namespace.
Bug fixes:
- "flattening" the big-query rows didn't flatten rows of arrays
> [GH-1221] import snapshots into a workspace

- api/src/wfl/service/datarepo.clj
- api/test/wfl/integration/datarepo_test.clj
The purpose of this ticket is to allow snapshot creation to use a datetime field rather than a date field for creation. 
This is for ticket https://broadinstitute.atlassian.net/browse/GH-1269
Using datetime field instead of date field for selecting rows to use in creation of a dataset snapshot
Nothing special
> Snapshot creation uses datetime rather than date

- api/src/wfl/module/sg.clj
- api/test/wfl/integration/modules/sg_test.clj
[GH-1278] Fix SG update-workload! implementation from trying to update clio BAM records for each Succeeded workflow repeatedly by restoring the :finished guard for register-workload-in-clio.
Introducted in [GH-1277].
[GH-1278]: https://broadinstitute.atlassian.net/browse/GH-1278
[GH-1277]: https://broadinstitute.atlassian.net/browse/GH-1277
> [GH-1278] Fix SG update-workload! implementation from updating Clio multiple times

- api/Dockerfile
The `Dockerfile` is being invoked in the root directory - we don't need
to add the parent directory, just the current one.
> [GH-1284] Fix docker image generation

- api/src/wfl/server.clj
Catch all throwables to make sure a workload failure doesn't bring down
workflow-launcher.
> [GH-1277] Prevent update loop from terminating

- api/build/build.clj
- api/src/wfl/util.clj
https://broadinstitute.atlassian.net/browse/GH-1273
To discourage the use of `util/do-or-nil-silently`, moved this macro to `build.clj`.  Interested developers should instead use `util/do-or-nil` in their applications.
- As described above.
- Build should complete successfully.
> util/do-or-nil-silently should move to build.clj

- api/src/wfl/service/firecloud.clj
- api/src/wfl/service/google/bigquery.clj
- api/src/wfl/util.clj
- api/test/wfl/integration/firecloud_test.clj
- api/test/wfl/unit/utils_test.clj
https://broadinstitute.atlassian.net/browse/GH-1226
To support submission creation for >1 entity, we must submit the entity references to FireCloud as an entity set (see [`TsvTypes.MEMBERSHIP`](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/src/main/scala/org/broadinstitute/dsde/firecloud/service/TSVFileSupport.scala#L13-L20
) in `firecloud-orchestration`).  The resulting entity set is itself a single entity which can be used in submission creation.
FireCloud's [membership type import code](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/src/main/scala/org/broadinstitute/dsde/firecloud/EntityService.scala#L140-L162) shows us that if we've specified the tsv type correctly, then we can specify one entity reference per line and the upload will …
> GH-1226 Support entity set creation when creating submissions.

- api/src/wfl/environment.clj
- api/src/wfl/service/rawls.clj
- api/test/wfl/integration/rawls_test.clj
TDR = Terra Data Repository
TW = Terra Workspace
For my ticket shared above as well as other COVID tickets to do and in progress, we will want to communicate directly with the Rawls API to interact with snapshots from TDR.
The general relationship between values in snapshot-land:
- An existing snapshot in TDR will be identified by a **snapshot-id**.
- When we link it in a TW, we will supply a **name**: subsequent attempts to import a snapshot with the same name will fail with a 409.
- When the snapshot is linked, we will get back a **reference-id**, the linked snapshot's unique ID within the TW.  This is the value Rawls expects when we fetch snapshot information or delete the snapshot from its TW.  Note that I couldn't see the …
> [GH-1215] Add wfl.service/rawls.clj for interacting directly with Rawls API

- api/src/wfl/service/rawls.clj
- api/test/wfl/integration/rawls_test.clj
@rexwangcc commented in my [last PR](https://github.com/broadinstitute/wfl/pull/370) to flag `rawls/create-snapshot` naming as being confusing.  I agree: we create the snapshot in the TDR, and link to it in the workspace via Rawls.
- Rename `rawls/create-snapshot -> create-snapshot-reference`: this is consistent with the [Rawls endpoint](https://rawls.dsde-dev.broadinstitute.org/#/snapshots/createDataRepoSnapshot) detailed descriptions and makes it more clear why reference IDs are being returned / passed around.
- Do we like this naming better?  Open to other suggestions, or "I like the old name".
- If using the old reference in your local development, take note.
> [GH-1215] Rename rawls/create-snapshot -> create-snapshot-reference

- api/test/wfl/integration/firecloud_test.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1293
Simply getting the submission again is not sufficient to guarantee that
the workflow has been queued for execution. Poll instead.
This is the same issue as https://broadinstitute.atlassian.net/browse/GH-1212
> [GH-1293] fix test-create-submissions-for-entity-set

- api/build/build.clj
- api/module.mk
- docs/md/dev-release.md
- ops/cli.py
- ui/module.mk
Update documentation and infrastructure for release candidates
- creating release candiates
- bashing release candidates
Restore version override in cli.py.
Re-tag latest docker images in cli.py so that version can be overwritten.
Update IMAGES target in Makefile to add the :latest tag. This is the image that will be tagged when we run cli.py tag-and-push-images.
Clean up :latest images on distclean target.
> Update documentation and infrastructure for release candidates

- api/src/wfl/module/covid.clj
- api/src/wfl/service/rawls.clj
- api/test/wfl/integration/modules/covid_test.clj
- api/test/wfl/integration/rawls_test.clj
- database/changesets/20210422_TerraDataRepoSourceDetailsTable.xml
- database/changesets/20210422_TerraExecutorDetailsTable.xml
My component of the COVID update loop: importing TDR snapshots to the workspace.  I consider it safe to merge, but is subject to change if/when the data model evolves further and we connect the pieces of the update loop.
Directly upstream from me:
- [Workflow creation](https://broadinstitute.atlassian.net/browse/GH-1213)
- [Polling for TDR snapshots](https://broadinstitute.atlassian.net/browse/GH-1222)
- Data model change: a `snapshot_reference_id` is linked to a workspace and should be associated with the executor, not the source (TDR in our use case).
- `covid/get-imported-snapshot-reference` -  nil or snapshot reference from Rawls for `snapshot_reference_id` in executor details instance (to be created from `TerraExecutorDetails`).
- …
> [GH-1215] Import snapshots within COVID workload

- api/src/wfl/module/covid.clj
- api/src/wfl/service/rawls.clj
- api/test/wfl/integration/modules/covid_test.clj
Main focus was fleshing out `update-terra-executor` to include snapshot import and sketch the update pattern.  As part of this work I got a better understanding of how we intend to use queues to pass items from source to executor and executor to sink.
Full functionality depends on [Rex's PR](https://github.com/broadinstitute/wfl/pull/371) for:
- New snapshot naming convention
- Reintroduction of `snapshot_id` to source details table
- Added `update-terra-executor` and required helpers: coerce an available snapshot from `source` queue to a snapshot reference, add entry point for submission creation (@tbl3rd) and write new workflows to executor details instance.
- Refined queue peek and pop for source and executor based on @ehigham 's …
> [GH-1215] COVID `update-terra-executor` progress

- api/src/wfl/api/handlers.clj
- api/src/wfl/api/workloads.clj
- api/src/wfl/module/aou.clj
- api/src/wfl/module/arrays.clj
- api/src/wfl/module/batch.clj
- api/src/wfl/module/copyfile.clj
- api/src/wfl/module/covid.clj
- api/src/wfl/module/sg.clj
- api/src/wfl/module/wgs.clj
- api/src/wfl/module/xx.clj
- api/src/wfl/service/postgres.clj
- api/src/wfl/service/rawls.clj
- api/test/wfl/integration/modules/aou_test.clj
- api/test/wfl/integration/modules/arrays_test.clj
- api/test/wfl/integration/modules/copyfile_test.clj
- api/test/wfl/integration/modules/covid_test.clj
- api/test/wfl/integration/modules/sg_test.clj
- api/test/wfl/integration/modules/wgs_test.clj
- api/test/wfl/integration/modules/xx_test.clj
- api/test/wfl/tools/workloads.clj
- api/test/wfl/unit/api_handlers_test.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1306
Add workflows multimethod
Change all locations where workflows are accessed via the `:workflows` keyword to use this function.
Implement `workflows` for COVID
- I've added a simple test to make sure the SQL is correct
- Awaiting executor implementation to test with more than 0 workflows.
> [GH-1306] Add `workflows` multimethod for workloads

- api/src/wfl/api/handlers.clj
- api/src/wfl/api/routes.clj
- api/src/wfl/api/workloads.clj
- api/src/wfl/module/aou.clj
- api/src/wfl/module/arrays.clj
- api/src/wfl/module/batch.clj
- api/src/wfl/module/copyfile.clj
- api/src/wfl/module/covid.clj
- api/src/wfl/module/sg.clj
- api/src/wfl/module/wgs.clj
- api/src/wfl/module/xx.clj
- api/test/wfl/integration/modules/sg_test.clj
- api/test/wfl/integration/modules/wgs_test.clj
- api/test/wfl/system/v1_endpoint_test.clj
- api/test/wfl/tools/endpoints.clj
- api/test/wfl/tools/workloads.clj
- api/test/wfl/unit/api_handlers_test.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1314
Adding a separate `workflows` selector will allow us to decouple the workload representation from serialisation artefacts that aren’t useful for a user.
In this PR, I'm changing
```
GET /api/v1/workloads
```
to only return workload metadata (everything but the workflows) and adding
```
GET /api/v1/workloads/{uuid}/workflows
```
to fetch the workflows in the workload.
Below is the swagger UI with the new endpoint.
> [GH-1314] expose workflows via `GET /api/v1/workload/{uuid}/workflows`

- api/src/wfl/module/covid.clj
- api/src/wfl/service/datarepo.clj
- api/test/wfl/integration/modules/covid_test.clj
- api/test/wfl/unit/modules/covid_test.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1317
The `source` of the workload needs to be told that the workload has been started so it can start looking in he datarepo for new data.
I've added a new multi-method for the source to start it, called on `start-workload!`. This writes `last_checked` to be the time when we should start listening for new data.
> [GH-1317] start the workload source

- api/src/wfl/module/covid.clj
- api/test/wfl/integration/modules/covid_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1315
Overview of new method `update-terra-workflow-statuses!`, called at the end of `update-terra-executor`:
1. Fetch executor details workflow records with active or failed status.
2. For each record, use Firecloud to fetch an up-to-date workflow.
3. Update the record's status using the workflow object.
Initially I thought I'd use @ehigham 's new code added in [this PR](https://github.com/broadinstitute/wfl/pull/396), but ended up going another way.
- See above.
- Supplemented existing integration tests.
- Run affected integration tests.
- I will add comments inline to flag possibly-debatable choices.
> TerraExecutor/update-executor should update active, failed workflow statuses

- api/src/wfl/module/covid.clj
- api/test/wfl/integration/modules/covid_test.clj
https://broadinstitute.atlassian.net/browse/GH-1307
https://broadinstitute.atlassian.net/browse/GH-1312
When creating submissions from snapshots, we have to modify the method configuration to specify the snapshot reference's name. Because Terra is an interactive tool, that same method config can be modified by a user at the same time.
I used the COVID demo script's method configuration updating as a starting point, to which I added additional checks for method configuration existence and version matching, as well as DB updating.
In new method `update-method-configuration`:
1. GET the method configuration from Firecloud (presently includes verification that the method configuration exists, but should be moved to `verify-terra-executor!` when available).
2. Throw if the Firecloud-derived …
> GH-1307 GH-1312 Update method configuration using snapshot reference

- api/src/wfl/module/covid.clj
- api/test/wfl/integration/modules/covid_test.clj
- database/changelog.xml
- database/changesets/20210519_ListSourceType.xml
- database/changesets/20210519_TDRSnapshotListSourceEnum.xml
RR: https://broadinstitute.atlassian.net/browse/GH-1322
In this change, I'm adding a new `source` to workflow-launcher that's a list of snapshots. It's requested as follows:
```json
"source": {
"name": "TDR Snapshots",
"snapshots": [
"00000000-0000-0000-0000-000000000000",
...
]}
```
It's implemented by instantiating a `ListSource` in the database, storing the edn of the snapshot.
I need https://github.com/broadinstitute/wfl/pull/400 and https://github.com/broadinstitute/wfl/pull/379 to finish this.
> [GH-1322] TDR Snapshots Source

- api/src/wfl/module/covid.clj
- api/test/wfl/integration/modules/covid_test.clj
- api/test/wfl/tools/workloads.clj
- database/changesets/20210422_TerraDataRepoSourceTable.xml
RR: https://broadinstitute.atlassian.net/browse/GH-1318
Add `stop-source` multimethod and implement for the TerraDataRepoSource.
When stopped, the source will stop looking for new rows to snaphot in
the TDR.
Also added logic for when the workload is finished. In this case, once
started the workload is finished when it has been stopped and both
source and executor queues are empty. To do this, I added another
multimethod to return the length of the queues.
For the executor, the length of the queue is the number of workflows
that have not been consumed or aborted.
For the source, the length of the queue is the number of unconsumed
records whose snapshot job is not 'failed'.
Note that this is slightly at odds with peek, where peek is meant to
return objects that are ready to be consumed.
> [GH-1318] Stop Workload Source

- api/src/wfl/module/covid.clj
- api/test/wfl/integration/modules/covid_test.clj
- api/test/wfl/tools/workloads.clj
The purpose of this PR is to add flags for skipping validation to source, executor and sink requests.
This is for ticket GH-1299
I improved several of the tests for validation and also added flags and tests for skipping validation
Please review this ticket for functionality - does it cover all of the things that it should? Also, for code improvements - is there a better way of writing what I did and if so, what is it?
> Adding flags for skipping validation of source, executor and sink in requests

- api/src/wfl/module/covid.clj
- api/test/wfl/integration/modules/covid_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1316
Launch submissions from Rawls snapshot references after updating the method configuration with the reference's name and an incremented version.  I used the [COVID demo script](https://github.com/broadinstitute/wfl/blob/develop/api/test/wfl/system/cdc_covid19_surveillance_demo.clj#L82) as a starting point.
Because we already had code to write records to the executor details table from a snapshot, this PR was less involved than I anticipated.
- Fully implemented `create-submission!` stub, pulling in existing `update-method-configuration!`.
- Per earlier PR feedback, simplified code which passed around updated executor with incremented method configuration version.  We don't expect the executor object passed from `update-executor! -> …
> GH-1316 Create submission within TerraExecutor update

- api/src/wfl/module/covid.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1333
Caused by database changes not propagated to source code. Destructing
old keys for the source lead to null values.
> [GH-1333] Fix NullPointerException in TDR Source

- api/src/wfl/module/covid.clj
- api/test/wfl/integration/modules/covid_test.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1336
Our BigQuery query was wrong as we were simply calling `toString` on a java.sql.Timestamp. This lead to queries like
```sql
SELECT (datarepo_row_id)
FROM `tdr-prod-workflow-launcher-dev.datarepo_ehigham_covid_bashing.flowcells`
WHERE last_modified_date BETWEEN '2021-05-26 15:31:18.287641' AND '2021-05-26T20:00:13'
```
The space in the interval was causing the problem and BigQuery interpreted that as a date. The fix is to ensure the lower and upper bound of our query-between interval is of the same type by coercing java.sql.Timestamp `last_checked` into a java.time.OffsetDateTime.
> [GH-1336] Fix continual snapshot creation

- api/test/wfl/system/v1_endpoint_test.clj
Fix these.
- https://broadinstitute.atlassian.net/browse/GH-1342
- https://broadinstitute.atlassian.net/browse/GH-1343
- Fix ^:private typo on test-covid-workload system test.
- Use consistent namespaces for workspace and method configuration.
- Run `clojure -M:test --focus wfl.system.v1-endpoint-test/test-covid-workload` against a local server.
- (-Ensure I didn't check in debugging code?-)
> GH-1342: Let test-covid-workload run in parallel and fix its method configuration namespace.

- api/src/wfl/module/covid.clj
- api/test/wfl/integration/modules/covid_test.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1350
The "Terra Workspace" sink validation did not validate that the
attributes listed in `fromOutputs` exist in the specified entity
type in the workspace. This PR fixes this.
> [GH-1350] fix Terra Workspace sink validation

- api/src/wfl/api/spec.clj
- api/test/wfl/system/v1_endpoint_test.clj
- api/test/wfl/tools/workloads.clj
- api/test/wfl/unit/modules/covid_test.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1354
This guards against erroring while creating snapshots if a user
makes a typo.
> [GH-1354] Enforce `snapshotReaders` are email addresses

- api/src/wfl/api/spec.clj
- api/src/wfl/module/covid.clj
- api/test/wfl/integration/modules/covid_test.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1357
I assumed (wrongly) the way Rawls represented workflows in a submission
was the same as how cromwell represented workflows. I also mocked these
representations incorrectly in tests. To fix this, only use the submission
to fetch workflow IDs, then use firecloud's workflow and workflow/outputs
endpoints so we don't have to adapt/mock multiple data models.
> [GH-1357] Fix failure to sink workflow outputs

- api/src/wfl/module/covid.clj
- api/src/wfl/service/firecloud.clj
- api/src/wfl/service/rawls.clj
- api/test/wfl/integration/modules/covid_test.clj
- api/test/wfl/integration/rawls_test.clj
- api/test/wfl/system/cdc_covid19_surveillance_demo.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1359
When sinking a resubmitted workflow, the TerraWorkspaceSink would
append to the existing entity in the workspace. This leaves the entity
in an even more wrong state than the reason the sample was reanalysed.
Our fix (as agreed with cloreth) is to clobber the entity in the
workspace by deleting the entity if it exists then upserting the new one.
> [GH-1359] Overwrite Workspace Entity On Sink

- docs/readme.md
When reviewing the [release candidate](https://github.com/broadinstitute/wfl/pull/415) I found that the readme I added for building our GitHub Pages documentation site had a broken command.
```
docs okotsopo$ python3 pip install -r requirements.txt
/usr/local/bin/python3: can't open file '/Users/okotsopo/wfl/docs/pip': [Errno 2] No such file or directory
```
I've fixed it here and would like to cherry-pick to the release branch. 
```
docs okotsopo$ python3 -m pip install -r requirements.txt
Requirement already satisfied: pymdown-extensions>="8.0" in…
```
- Fix broken requirements install command in `docs/readme.md`
> Fix broken requirement install command in docs readme

- api/test/wfl/integration/modules/arrays_test.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1361
This is a low risk change for v0.7.0 as this test doess not exercise
reachable product code.
Disabling:
- wfl.integration.modules.arrays-test/test-update-arrays-workload!
> [GH-1361] Disable Failing Tests for v0.7.0 Release

- api/src/wfl/util.clj
- api/test/wfl/integration/firecloud_test.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1363
Caused by firecloud returning "Launching" as a workflow status - we were
testing that the status was in #{"Queued" "Submitted"}.
Fix `util/poll` so logical FALSE can be returned from the action.
> [GH-1363] Fix Sporadic Firecloud Test Failures

- api/test/wfl/system/automation_test.clj
- api/test/wfl/tools/workloads.clj
- https://broadinstitute.atlassian.net/browse/GH-1332
Previously `wfl.tools.workloads/when-done` terminated prematurely if called immediately after starting a workload, when a workload does not yet have workflows.  This behavior was obscured when interacting with the test in debug mode with breakpoints. 
Within `wfl.tools.workloads/when-done`:
- If checking that all workloads are finished, also check that the workload list is nonempty
- Fixed incorrect reference to static `workload` object from workload creation: we instead want to examine the latest version of the workload
Within `wfl.system.automation-test`:
- Method configuration name was incorrect for the specified source workspace
- Workspace clone name uses source workspace name as its base
Assumes a running local WFL and Postgres, …
> GH-1332 wfl.tools.workloads/when-done should not exit prematurely

- docs/md/modules-covid.md
- docs/md/workload.md
This is to reorder the fields in the documentation of the executor block for clarity
Please make sure that I didn't delete anything.
> Changing order of executor block in docs

- api/test/wfl/system/automation_test.clj
- api/test/wfl/system/v1_endpoint_test.clj
- api/test/wfl/tools/workloads.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1398
Split `workloads/when-done` into two functions:
- one that polls until the workload is :finished
- another that polls all the workflows
Add an assertion to the automation-test
> [GH-1398] Fix `test-start-aou-workload` from polling forever

- api/src/wfl/executor.clj
- api/test/wfl/integration/executor_test.clj
- database/changelog.xml
- database/changesets/20210624_AddRetryToTerraExecutorDetails.xml
- makerules/modules.mk
RR: https://broadinstitute.atlassian.net/browse/GH-1401
Verified that this change affects all existing tables created from that type.
When workflows are requested, only the non-retried workflows are returned.
Note that unconsumed workflows are still visible to downstream. Note sure what the correct behaviour should be here.
> [GH-1401] Add `retry` Attribute to TerraExecutorDetails Type and Instances Thereof

- api/src/wfl/api/spec.clj
- api/src/wfl/module/batch.clj
- api/src/wfl/source.clj
There were a few residual namespace issues resulting from splitting the specs out of the spec.clj file. This rectifies them.
Fix straggler namespace issues
- No changes.
> Fix some namespace issues

- api/src/wfl/api/handlers.clj
- api/src/wfl/api/routes.clj
- api/src/wfl/api/spec.clj
- api/src/wfl/module/all.clj
- api/src/wfl/service/cromwell.clj
- api/src/wfl/service/rawls.clj
- api/src/wfl/util.clj
- api/test/wfl/system/v1_endpoint_test.clj
- api/test/wfl/tools/endpoints.clj
- api/test/wfl/unit/utils_test.clj
Make it easier to filter workflows by status. Also in this PR is work to bring the cromwell statuses up to date.
- https://broadinstitute.atlassian.net/browse/GH-1409
- https://broadinstitute.atlassian.net/browse/GH-1410
- Added new spec for a workflow query string
- Added query string to the route for GET workflows
- Modified the get-workflows handler function to call workflows-by-status if status is provided
- The workload/:uuid/workflows endpoint should work with status both provided and not provided. It should be verified that the endpoint returns results both when provided a status and not as well as verifying that it returns workflows with the correct status if it is provided.
> [GH-1409] Add Status Query String to workflows GET request

- api/src/wfl/util.clj
- api/test/wfl/tools/endpoints.clj
- api/test/wfl/unit/utils_test.clj
Updates the wfl-url function in the endpoints namespace to not use trim-slashes and removes the trim-slashes function from util.
- Remove trim-slashes function and unit test
- Remove use of trim-slashes from wfl-url
- Update endpoints in wfl.tools.endpoints by removing slashes from beginning and end of the url parts
> Remove trim-slashes and fix endpoints in wfl.tools namespace

- api/resources/log4j2.xml
- api/src/wfl/environment.clj
- api/src/wfl/jdbc.clj
- api/src/wfl/server.clj
- api/src/wfl/source.clj
- api/src/wfl/stage.clj
- https://broadinstitute.atlassian.net/browse/GH-1340
This PR adds meaningful `DEBUG` and `INFO` logs to the `source` namespace, with a focus on the `TerraDataRepoSource` update loop.  I will separately PR enhanced logging in the `executor` and `sink` namespaces after incorporating feedback received here.
- Added logging prefixes to flag source instance table and row ID where appropriate, e.g. `[TerraDataRepoSource id=2] …`
- Downgraded and removed logging where it did not provide value or buried meaningful logging
- Log timestamp altered to date plus 24 hour timestamp
An earlier version of this work yielded the following logs for a `TerraDataRepoSource` update loop run with no new rows to snapshot.  Environment variable reads and transaction opens / closes obscured useful information. …
> Logging added to source ns

- api/src/wfl/executor.clj
- api/src/wfl/jdbc.clj
- api/src/wfl/module/batch.clj
- api/src/wfl/service/datarepo.clj
- api/src/wfl/service/postgres.clj
- api/src/wfl/sink.clj
- api/src/wfl/source.clj
- api/test/wfl/integration/sinks/datarepo_sink_test.clj
- api/test/wfl/integration/sinks/workspace_sink_test.clj
- api/test/wfl/tools/fixtures.clj
- api/test/wfl/tools/workloads.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1413
Add load/create functions for the data repo sink.
I'm leaving `update-sink` to another PR as I think that'll be a more complicated change that I'd like reviewed separately.
I'm also deferring how to disambiguate between `stage/validate` implementations to another PR as it may involve a slight redesign.
> [GH-1314] Start Implementing DataRepo Sink

- api/src/wfl/executor.clj
- api/test/wfl/integration/executor_test.clj
- api/test/wfl/integration/modules/covid_test.clj
- api/test/wfl/system/cdc_covid19_surveillance_demo.clj
- https://broadinstitute.atlassian.net/browse/GH-1414
Fallback to importing an existing snapshot reference when creation fails with a 409 (duplicate resource exception) stopped working.
- Calling `rawls/create-or-get-snapshot-reference` rather than `rawls/create-snapshot-reference` to fall back to fetching an existing snapshot reference on a 409 error.
- Mocking in testing updated to mock `rawls/create-or-get…` rather than `rawls/create…`.  This previous mocking allowed tests to pass as the creation method is called within the create-or-get, but we weren't mocking what was actually being called.  If this method call is incorrectly changed back in the future, tests will fail.
I tested manually:
- Create and start a workload that tries to import a snapshot as a reference with the same name …
> GH-1414 Executor falls back to fetching existing snapshot reference

- api/src/wfl/executor.clj
- api/test/wfl/integration/executor_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1419
Background is documented pretty extensively in the linked ticket, please take a look.
In `wfl.executor/terra-executor-queue-length`:
- Postgres needs us to explicitly consider workflows with null status.
In `wfl.integration.executor-test`:
- Added new test `test-terra-executor-queue-length` to confirm that workflow records missing status and/or uuid are still included in the count.
- Tangentially, corrected faulty assumption in mocking: Firecloud returns differently formatted workflows depending on whether they are fetched as part of a submission fetch, or fetched individually.
Automated testing:
- Run `wfl.integration.executor-test/test-terra-executor-queue-length`
If interested in manually experimenting:
- Trigger a staged workload …
> [GH-1419] Terra Executor queue length should consider workflows with null status

- api/src/wfl/debug.clj
- api/src/wfl/server.clj
- api/src/wfl/source.clj
- api/src/wfl/util.clj
- api/test/wfl/integration/datarepo_test.clj
- api/test/wfl/integration/modules/covid_test.clj
- api/test/wfl/integration/source_test.clj
- api/test/wfl/tools/fixtures.clj
- docs/md/dev-process.md
- https://broadinstitute.atlassian.net/browse/GH-1397
- Document Swagger validation of API specs.
- Mock snapshot missing TDR rows.
- Expand query interval and filter out old rows.
- Start with wfl.integration.source-test/test-backfill-tdr-source.
- Evaluate how it mocks the problem.
- In wfl.source, evaluate how changes to find-new-rows and find-and-snapshot-new-rows address the problem.
- Perhaps back out wfl.source commits and watch the test-backfill-tdr-source test fail for more understanding.
> GH-1397: Sweep and snapshot dataset row IDs that were missed when polling a dataset

- api/src/wfl/api/handlers.clj
- api/src/wfl/api/routes.clj
- api/src/wfl/configuration.clj
- api/src/wfl/jdbc.clj
- api/src/wfl/log.clj
- api/src/wfl/server.clj
- api/test/wfl/unit/logging_test.clj
- database/changelog.xml
- database/changesets/20210720_AddConfigurationTable.xml
Adds configuration for setting the severity level of logs that are printed to stdout.
Added a configuration table for key value pairs. Currently used to hold a logging level config.
Added a logging-level atom to the log namespace to limit messages to only enabled severity levels.
Added endpoints for getting the current logging level and updating/inserting configurations.
Added a timed check for current level to set the current logging level from the configuration table.
Verify that all tests pass.
Verify that the logging_level GET and POST request return the current level and set the current level respectively.
Verify that no messages below the current level print to stdout (give time for the delay after changing the level).
> [GH-1139] Logging level and configuration

- api/src/wfl/service/datarepo.clj
- api/src/wfl/sink.clj
- api/src/wfl/source.clj
- api/src/wfl/workflows.clj
- api/test/wfl/integration/datarepo_test.clj
- api/test/wfl/integration/executor_test.clj
- api/test/wfl/integration/modules/covid_test.clj
- api/test/wfl/integration/sinks/datarepo_sink_test.clj
- api/test/wfl/integration/sinks/workspace_sink_test.clj
- api/test/wfl/tools/queues.clj
- api/test/wfl/tools/workflows.clj
- api/test/wfl/tools/workloads.clj
- api/test/wfl/unit/mime_type_test.clj
- api/test/wfl/unit/sink_test.clj
- api/test/wfl/unit/workflows_test.clj
- database/changesets/20210709_TerraDataRepoSink.xml
RR: https://broadinstitute.atlassian.net/browse/GH-1415
This change contains a rough implementation of the TerraDataRepo sink update functionality. After discovering certain hurdles in the original design, I've made some tweaks and incorporated TDR's work https://broadworkbench.atlassian.net/browse/DR-1960 so that we only need one ingest request instead of separately loading the output files and output metadata. At the time of writing, DR-1960 is work in progress so our ingests won't work just yet.
Some things to call out in this change that I'm deferring to a follow up change into the feature branch:
- I need to upload the json file for TDR to ingest. I'm currently using our test outputs bucket as a temporary folder for this which is obviously not a production-ready solution. Possible …
> [GH-1415] Implement `update-sink` for TerraDataRepoSink

- api/src/wfl/api/handlers.clj
- api/src/wfl/executor.clj
- api/src/wfl/module/covid.clj
- api/src/wfl/service/cromwell.clj
- api/src/wfl/service/postgres.clj
- api/src/wfl/stage.clj
- api/test/wfl/integration/executor_test.clj
- api/test/wfl/integration/modules/covid_test.clj
- api/test/wfl/system/v1_endpoint_test.clj
- docs/md/usage-retry.md
- Ticket [GH-1394](https://broadinstitute.atlassian.net/browse/GH-1394)
- @tbl3rd's [spike doc](https://broadinstitute.atlassian.net/wiki/spaces/GHConfluence/pages/2674393095/Retries+in+Terra+WFL) -- thanks!
- Rhian's [original PR](https://github.com/broadinstitute/wfl/pull/472) which this replaces -- thanks!
Retry functionality is now supported in staged workflows within their executors, with COVID workloads altered to take advantage.
`TerraExecutor` retry resubmits the snapshot reference associated with the specified workflows, and updates each original workflow record to point to its retry record.  The existing update loop will handle updating workflow uuids and statuses for us.
In `wfl.handlers/post-retry`:
- Raise HTTP 400 if passing in an unsupported status, or if no workflows …
> [GH-1394] TerraExecutor retry implementation and Sarscov2IlluminaFull integration

- docs/md/executor.md
- docs/md/index.md
- docs/md/modules-covid.md
- docs/md/staged-workload.md
- docs/md/usage-retry.md
- docs/mkdocs.yml
- docs/readme.md
- [GH-1395](https://broadinstitute.atlassian.net/browse/GH-1395) Document the new WFL retry capability for users.
- [GH-1428](https://broadinstitute.atlassian.net/browse/GH-1428) Staged workflow GitHub pages should be pulled into navigation
Following implementation of Terra executor retry functionality and COVID `/retry` endpoint in https://github.com/broadinstitute/wfl/pull/482, I looked at our public documentation to see what updates were needed.  I also addressed existing omissions and opportunities for better clarity.
Staged workflows
- Not all workloads are staged workloads, update throughout to reflect this distinction
- Add pages to the site navigation
Executor
- Added new retry method to protocol representation
Retry usage
- Reorganization to allow for anchor links from other …
> [GH-1395] GitHub Pages updates: COVID, staged workflows, retry functionality

- api/src/wfl/executor.clj
- api/src/wfl/module/covid.clj
- api/src/wfl/sink.clj
- api/src/wfl/source.clj
- api/src/wfl/stage.clj
- api/test/wfl/integration/executor_test.clj
- api/test/wfl/integration/modules/covid_test.clj
- api/test/wfl/integration/sinks/datarepo_sink_test.clj
- api/test/wfl/integration/sinks/workspace_sink_test.clj
- api/test/wfl/integration/source_test.clj
- api/test/wfl/system/v1_endpoint_test.clj
- api/test/wfl/tools/workloads.clj
RR: https://broadinstitute.atlassian.net/browse/GH-1430
Remove `stage/validate-or-throw` and inline their implementations in their respective `create-X` functions.
This is done because
- we were losing context (ie. was this a source/sink/executor) and had a collision in the tdr sink and source impls
- these multimethods didn't really make sense and require some redesign work
> [GH-1430] Remove `stage/validate-or-throw` and inline their implementations into `create-X`.

- api/src/wfl/api/handlers.clj
- https://broadinstitute.atlassian.net/browse/GH-1394
Per @ehigham QA feedback, retry error maps reference the workload UUID as `workload` rather than `uuid` for better specificity.
```
wm111-e35:wfl okotsopo$ curl -X POST "http://localhost:3000/api/v1/workload/e66c86b2-120d-4f7f-9c3a-b9eaadeb1919/retry"         -H 'Authorization: Bearer '$(gcloud auth print-access-token)         -H "Content-Type: application/json"         -d '{ "status": "Succeeded" }'
{
"uri" : "/api/v1/workload/e66c86b2-120d-4f7f-9c3a-b9eaadeb1919/retry",
"message" : "Retry unsupported for requested status.",
"details" : {
"workload" : "e66c86b2-120d-4f7f-9c3a-b9eaadeb1919",
"supported-statuses" : [ "Failed", "Aborted" ],
"requested-status" : "Succeeded"
}
}wm111-e35:wfl okotsopo$ curl -X POST …
```
> ENG-1394 Update post-retry error maps per QA feedback

- .github/workflows/doc-site.yml
- Github actions should build docs on develop.
- I looked into [how `mkdocs` uses `mike` as a versioning manager](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/?h=version), but it introduces too much complication into our build workflow, so maybe we should just deploy docsite on pushing to `develop`.
> Github actions should build docs on develop.

- api/src/wfl/service/cromwell.clj
- docs/md/index.md
- docs/md/usage-retry.md
- docs/mkdocs.yml
- https://broadinstitute.atlassian.net/browse/GH-1439
- Succeeded workflows are now permissible to retry
- Updated public-facing documentation to reflect this
- While working on docs, removed references to now-deleted frontend documentation page
I ran the retry system tests `wfl.system.v1-endpoint-test/test-retry-*-workload` and they all succeeded.  Example output:
```
$ WFL_WFL_URL=http://localhost:3000 clojure -M:test --focus wfl.system.v1-endpoint-test/test-retry-wgs-workload
--- system (clojure.test) ---------------------------
wfl.system.v1-endpoint-test
test-retry-wgs-workload
retry-workflows fails (400) when workflow status unsupported
retry-workflows fails (400) when no workflows for supported status
1 tests, 14 assertions, 0 failures.
```
I also executed a COVID workload with a …
> GH-1439 Succeeded workflow status should be permissible to retry

- api/test/wfl/integration/executor_test.clj
- api/test/wfl/integration/modules/covid_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1454
Description of the cause in the ticket.
- Bump method configuration 1->2 in automated tests where [this](https://app.terra.bio/#workspaces/wfl-dev/CDC_Viral_Sequencing/workflows/wfl-dev/sarscov2_illumina_full) method configuration is accessed
I reran the automated tests locally, those which failed now succeed.
> GH-1454 Update integration tests to reflect updated COVID method config

- database/changelog.xml
- database/changesets/20210910_AddRetryToTerraDataRepoSourceDetails.xml
- https://broadinstitute.atlassian.net/browse/GH-1450
In preparation for automatic retries of failed snapshot creation jobs within `TerraDataRepoSource`'s update loop, added a retry column to the `TerraDataRepoSource` type and its instances.
I looked at all existing queries of this source details table (details table peek and queue length).  I found nowhere that needed an additional filter to exclude retried snapshot creation jobs, since we will only be automating retries for failed (and as such, never-to-be-consumed) jobs.
*However*, it might be worth codifying this filter if we think we might ever support API-driven retry of snapshot creation jobs, specifically successful ones.  LMK if you'd like me to make this change.
Prior to this change, I executed a COVID workload with a …
> GH-1450 Add retry attribute to TerraDataRepoSource type and instances

- docs/md/usage-retry.md
- https://broadinstitute.atlassian.net/browse/GH-1373
- Fixed `removeSucceeded()` to do the right thing.
- Maybe extract the documented code to a shell script file, replace the `curl` with a `cat`, then run it like this?
`script uuid=1ea3b3a4-e5b3-4911-a52b-11470105a0c3 https://dev-wfl.gotc-dev.broadinstitute.org/`
Verify you see a valid workload request for any `"Failed"` workflows … or something.
> GH-1373: Keep non-null inputs and options from "Failed" workflows.

- api/src/wfl/module/aou.clj
- api/test/wfl/tools/workloads.clj
- https://broadinstitute.atlassian.net/browse/GH-1452
- Just did what it says.
> GH-1452: Bump AoU Arrays.wdl version to 2.4.1 to drop default genotype_concordance_threshold to 0.95.

- api/src/wfl/service/slack.clj
- api/src/wfl/source.clj
- api/src/wfl/util.clj
- api/test/wfl/integration/source_test.clj
- api/test/wfl/unit/source_test.clj
- docs/md/source.md
- https://broadinstitute.atlassian.net/browse/GH-1444
Workloads are universally updated every 20 seconds at present, but polling the TDR that frequently for rows to snapshot can lead to problems, as we've found now that the COVID workload has been running in real life for a week:
- More likely that we create many single-row / low-cardinality snapshots, which then spawn multiple submissions.  Harder for stakeholders to keep track (not to mention, smells funny).
- A snapshot creation job carries with it an exclusive lock on the entire dataset.  More snapshotting = more locks = more possibilities of collision (WFL vs. WFL or WFL vs. externally-managed ingests).
Feedback from COVID and eMerge stakeholders has been to suggest polling every 20 minutes for new rows instead of every 20 seconds, …
> GH-1444 TerraDataRepoSource should snapshot less frequently

- docs/md/usage-retry.md
- https://broadinstitute.atlassian.net/browse/GH-1373
As the retry runbook no longer removes successful workflows, but keeps the failed ones, renamed the function accordingly. 
I spun up a local docsite and followed the instructions in my [QA comment](https://broadinstitute.atlassian.net/browse/GH-1373?focusedCommentId=1262242).
> GH-1373 rename removeSucceeded in retry runbook

- api/src/wfl/log.clj
- api/test/wfl/unit/logging_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1448
- Hack how JSONWriter handles Throwables.
- Watch https://www.youtube.com/watch?v=V4WGsMplGxU
> GH-1448: Exceptions fail to be logged as JSON.

- api/src/wfl/sink.clj
- api/test/resources/workflows/illumina_genotyping_array/inputs.json
- api/test/wfl/integration/datarepo_test.clj
- api/test/wfl/integration/sinks/datarepo_sink_test.clj
In the TDR Sink PR, there were a couple of changes to which buckets some of the test inputs come from. These changes were not correct, as the bucket that was being used has a 14 day lifecycle. This PR reverts those bucket changes.
Related PR: https://github.com/broadinstitute/gotc-deploy/pull/309
Related Ticket: https://broadinstitute.atlassian.net/browse/GH-1475
In making these changes, it was found that there was an integration test that was giving a false negative result. The test was checking that a UserException was thrown when there would not be because the ingest succeeds. This PR contains the rework of the test to correctly check for UserException on an actual failing ingest.
- Restore the buckets used to ingest inputs into TDR Sink test datasets
- Rework `update-datarepo-sink` …
> Update test inputs buckets

- docs/md/executor.md
- docs/md/modules-covid.md
- docs/md/usage-retry.md
- https://broadinstitute.atlassian.net/browse/GH-1516
Documenting `/retry` behavior changes stemming from https://github.com/broadinstitute/wfl/pull/525
Namely, Terra submission ID is now a required filter, and workflow status is optional (and decorative).
Review is easiest off of a local docsite.  Per `docs/readme.md`:
```
make docs
. derived/.venv/docs/bin/activate && (  cd derived/docs; python3 -m mkdocs serve  )
```
Altered pages:
http://127.0.0.1:8000/executor/
http://127.0.0.1:8000/modules-covid/
http://127.0.0.1:8000/usage-retry/
Please read through and let me know if it makes sense.  I will merge following the v0.10.x release, when the corresponding functionality is live.
> GH-1516 Documentation updates - TerraExecutor retry

- api/src/wfl/sink.clj
- api/test/wfl/unit/sink_test.clj
During eMerge testing, an error occurred. This error was as a result of there being a null output in a fileref field. The null output was not specifically being handled when trying to create the request for the TDR sink and thus, an error was born.
https://broadinstitute.atlassian.net/browse/GH-1555
- Added null check to `rename-gather-bulk`
- Added test case from null output
- Run unit test `test-rename-gather-bulk`
> [GH-1555] add null check to rename-gather-bulk

- api/src/wfl/executor.clj
- api/test/wfl/integration/executor_test.clj
- api/test/wfl/unit/executor_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1560
`TerraExecutor` now sets a method configuration's `rootEntityType` to be the source snapshot's table.  Previously, it only set the `dataReferenceName` to be the snapshot reference's name, and the submission was triggered with whatever root entity table previously existed.
For a method configuration that has previously run successfully, this has worked with the prior table setting is used.  Here are a few ways this can go wrong:
- A fresh method configuration with no previous submissions may have this table unset
- Method configuration last triggered with a data table as its root entity type, not a snapshot
- Method configuration last triggered with a snapshot of a different TDR table
Edge case: if the `TerraExecutor` doesn't find …
> GH-1560 TerraExecutor tries to set root entity table on submission

- api/src/wfl/executor.clj
- api/src/wfl/module/covid.clj
- api/src/wfl/service/firecloud.clj
- api/src/wfl/sink.clj
- api/src/wfl/source.clj
- api/test/wfl/integration/executor_test.clj
- api/test/wfl/integration/sinks/datarepo_sink_test.clj
- api/test/wfl/integration/sinks/workspace_sink_test.clj
- api/test/wfl/integration/source_test.clj
- docs/md/executor.md
- docs/md/sink.md
- docs/md/source.md
We want to be able to utilize the user comment field in a Terra submission. In this comment, we would like to include the information necessary to be able to commence a retry such as workload uuid and environment. In order to accomplish this, WFL also needs to be updated to have the workload available for the submission creation to be able to send a user comment.
- (https://broadinstitute.atlassian.net/browse/GH-1540)
- Added user comment to submission creation
- Updated the three workload update functions (source, executor, sink) to be passed a workload instead of their object and upstream from the workload.
- Updated tests to accommodate
- Run tests
- Verify that a user comment with the workload uuid and the current running environment makes it into a Terra submission
> [GH-1540] Apply User Comments to Terra Submissions

- api/test/wfl/integration/datarepo_test.clj
- api/test/wfl/tools/fixtures.clj
- https://broadinstitute.atlassian.net/browse/GH-1433
In normal operations, WFL does not programmatically delete TDR snapshots.  The exception: within the `create-temporary-snapshot` fixture used to clean up in testing.
Deleting a snapshot obtains an exclusive lock on the underlying dataset, and can block other concurrent operations on that dataset.  We've seen `wfl.integration.datarepo-test/test-create-snapshot` fail when run concurrently for this reason since it used a fixed existing dataset.
Solution: test snapshot creation within a temporary dataset, per Trevyn's recommendation.
> GH-1433 Test TDR snapshot creation within temporary dataset

- docs/md/executor.md
- https://broadinstitute.atlassian.net/browse/GH-1598
In the process of testing the Twist/TCAP staged workload, we confirmed that WFL Firecloud groups don't need to be workspace "Owners", only "Writers".  Updated our documentation accordingly.
(Fine by me with the downgrade: owners can delete workspaces, better to not have the ability to do so accidentally.)
> [GH-1598] Update TerraExecutor documentation

- api/src/wfl/environment.clj
- api/src/wfl/service/slack.clj
- api/test/wfl/system/v1_endpoint_test.clj
- api/test/wfl/unit/slack_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1604
Any time we try to emit Slack notifications in WFL Dev or Prod, the Kubernetes pod restarts and we see this error message:
`java.lang.RuntimeException: Agent is failed, needs restart`
I'm hiding Slacking behind a feature switch at environment variable `WFL_SLACK_ENABLED`.  By default, we'll disable sending Slack notifications, instead emitting a log of what we would have sent.  To enable, set to "enabled".
If a WFL user creates a workload in the mean time with Slack watchers specified, we'll honor the request but not send anything to their channels.
If enough time, I'd like to create a patch release v0.14.1 and deploy to WFL dev today.
- Slacking now hidden behind feature switch to cut off agent failures driving Kubernetes pod restarts …
> [GH-1604] Disable / hide Slacking behind WFL_SLACK_ENABLED

- api/deps.edn
- api/src/wfl/api/handlers.clj
- api/src/wfl/api/routes.clj
- api/src/wfl/log.clj
- api/src/wfl/util.clj
- api/test/wfl/integration/datarepo_test.clj
- api/test/wfl/integration/modules/covid_test.clj
- api/test/wfl/system/v1_endpoint_test.clj
- api/test/wfl/tools/endpoints.clj
- api/test/wfl/unit/logging_test.clj
- api/test/wfl/unit/sink_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1622
- Fix bug in `wfl.log/level-string?`.
- Add a `wfl.unit.logging-test/endpoint` test.
- Expose the `logging_level` APIs in Swagger.
- Update reitit.
- Add some latent support for POST body data.
- Expose the `logging_level` APIs in Swagger.
- Remove some `:refer`s and cleverness.
- Run the acceptance tests against a local server.
- This PR will fail the `wfl.unit.logging-test/endpoint` test until WFL's deployed in dev.
> [GH-1622] No logs for you!

- api/src/wfl/executor.clj
- api/test/wfl/integration/executor_test.clj
- api/test/wfl/integration/modules/staged_test.clj
- api/test/wfl/system/automation_test.clj
- api/test/wfl/system/v1_endpoint_test.clj
- api/test/wfl/tools/workloads.clj
- database/changelog.xml
- database/changesets/20220228_TerraExecutorNullableMethodConfigVersion.xml
- docs/md/staged-api-usage.md
- docs/md/staged-executor.md
- docs/md/staged-workload.md
- https://broadinstitute.atlassian.net/browse/GH-1629
Previously, when creating a staged workload's `TerraExecutor` the caller first needed to query Firecloud API directly for their method configuration's present version.  The intention was to make up for a lack of audit trail for method configuration changes, to make debugging easier in the case that workflows started failing after a change.
User feedback indicated that this Firecloud fetch was one of the more annoying start-up costs of launching a staged workload, without much benefit.  I agree!
Now, we save the method configuration's version from Firecloud on workload creation rather than making the caller do the fetch themselves.  When triggering Terra submissions, if the method configuration has an unexpected version we log a warning …
> [GH-1629] TerraExecutor gets method configuration version from Firecloud

- api/src/wfl/executor.clj
- api/src/wfl/service/slack.clj
- api/test/wfl/integration/executor_test.clj
- api/test/wfl/unit/executor_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1618
Similar logging treatment as previously applied to staged workload source: https://github.com/broadinstitute/wfl/pull/579
`executor.clj`
- Many methods refactored to pass around `workload` which includes `executor`, rather than just the `executor`.
- Where appropriate, logs emitted within this stage are JSON rather than strings and include the workload's log representation.
- Updated automated tests accordingly.
Passed:
```
wm111-e35:wfl okotsopo$ make TARGET=system
…
export CPCACHE=/Users/okotsopo/wfl/api/.cpcache;            \
export WFL_WFL_URL=http://localhost:3000; \
clojure  -M:parallel-test wfl.system.v1-endpoint-test | \
tee /Users/okotsopo/wfl/derived/api/system.log
…
Ran 33 tests containing 374 assertions.
0 failures, 0 …
```
> [GH-1618] Add workload info to executor logs

- docs/requirements.txt
- https://broadinstitute.atlassian.net/browse/GH-1639
`jinja2` v3.1.0 was released today and included the removal of some deprecated code: https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0
But `mkdocs` is incompatible with this latest version (and we pin it anyways).  They're working on it: https://github.com/mkdocs/mkdocs/issues/2794
The impact on `wfl` is that `make docs` fails:
```
AttributeError: module 'jinja2' has no attribute 'contextfilter'
```
So, I pinned the last good `jinja2` version and the build succeeds once more.
A clean docs build should succeed:
```
cd /path/to/wfl
make distclean; make docs
```
> [GH-1639] Pin jinja2 version for mkdocks compatibility

- api/src/wfl/executor.clj
- https://broadinstitute.atlassian.net/browse/GH-1640
Whoops!
I broke Terra Submission links in completed workflow Slack messages when doing some light refactoring in https://github.com/broadinstitute/wfl/pull/591/files
Ran this test individually:
```
wm111-e35:api okotsopo$ WFL_WFL_URL=http://localhost:3000  clojure -M:test --focus   wfl.system.v1-endpoint-test/test-workload-sink-outputs-to-tdr
…
--- system (clojure.test) ---------------------------
wfl.system.v1-endpoint-test
test-workload-sink-outputs-to-tdr
1 tests, 7 assertions, 0 failures.
```
Verified that the emitted Slack message links all worked as expected (they won't work now if you click on them since the resources have since been cleaned up):
https://broadinstitute.slack.com/archives/C026PTM4XPA/p1648234413929859 …
> [GH-1640] Broken Terra Submission links in completed workflow Slack messages

- api/src/wfl/api/workloads.clj
- api/src/wfl/module/aou.clj
- api/src/wfl/module/batch.clj
- api/src/wfl/module/sg.clj
- api/src/wfl/module/staged.clj
- api/src/wfl/server.clj
- api/test/wfl/tools/workloads.clj
- https://broadinstitute.atlassian.net/browse/GH-1623
As a prerequisite to factoring out external calls from DB transactions, this PR forces `workloads/update-workload!` implementations to define their own transactions.
With these changes, this decoupling is complete for staged workloads.  Staged workloads can be updated in their own future in a separate PR.
Legacy workload update behavior otherwise remains the same.
Pass:
```
wm111-e35:wfl okotsopo$ make TARGET=system
export CPCACHE=/Users/okotsopo/wfl/api/.cpcache;            \
export WFL_WFL_URL=http://localhost:3000; \
clojure  -M:parallel-test wfl.system.v1-endpoint-test | \
tee /Users/okotsopo/wfl/derived/api/system.log
WARNING: Use of :paths external to the project has been deprecated, please remove: ../derived/api/src
WARNING: Use …
```
> [GH-1623] workloads/update-workload! should define own transactions

- api/src/wfl/executor.clj
- api/src/wfl/module/wgs.clj
- api/src/wfl/stage.clj
- api/src/wfl/util.clj
- api/test/wfl/integration/modules/staged_test.clj
- api/test/wfl/system/v1_endpoint_test.clj
- api/test/wfl/unit/logging_test.clj
- https://broadinstitute.atlassian.net/browse/GH-1644
- https://broadinstitute.atlassian.net/browse/GH-1645
- Upgrade to `ExternalWholeGenomeReprocessing_v2.0.5`.
- Delete unused code from `wfl.util`.
- Clean up random cruft I noticed recently.
- The new WGS pipeline takes a while to run.
> [GH-1645] Update wfl.module.wgs/workflow-wdl to allow overriding read_length in CollectRawWgsMetrics.

- api/src/wfl/service/datarepo.clj
- https://broadinstitute.atlassian.net/browse/GH-1653
Previously, one navigated directly to a TDR snapshot via the following path:
`https://<tdr-host>/snapshots/details/<snapshot-id>`
Recent changes in TDR have updated the path thusly (ticket: https://broadworkbench.atlassian.net/browse/DR-2436):
`https://<tdr-host>/snapshots/<snapshot-id>`
The impact of this change is that WFL’s “submission launched” Slack messages have broken links to the source snapshots.  Example:
https://broadinstitute.slack.com/archives/C031GKEHCKF/p1650995030978519
https://data.terra.bio/snapshots/details/1dea8d26-0e26-4816-b9d1-ce6d93e3756d
This fix would update the above link as follows:
https://data.terra.bio/snapshots/1dea8d26-0e26-4816-b9d1-ce6d93e3756d
> [GH-1653] TDR snapshot direct links have changed

- api/src/wfl/api/handlers.clj
- api/src/wfl/executor.clj
- api/src/wfl/service/datarepo.clj
- api/test/wfl/integration/source_test.clj
- api/test/wfl/system/v1_endpoint_test.clj
- api/test/wfl/unit/executor_test.clj
- docs/md/staged-source.md
- https://broadinstitute.atlassian.net/browse/GH-1678
- Factor out retry filter keys.
- Rename `terra-executor-workflows-sql-params` to `filter-query-for-unretried-workflows`.
- Privatize some "public for testing" vars.
- Prefix match `loadTag` with `LIKE` on snapshot queries.
- Document changes. 
- Start with `datarepo.clj` and `staged-source.md`.
- Scan the rest while ignoring whitespace changes.
> [GH-1678] When monitoring source load tags, match prefix instead of exact match. 

- api/deps.edn
- api/src/wfl/main.clj
- https://broadinstitute.atlassian.net/browse/GH-1692
- [GH-1691] Fix the SG/GDC increment the add_bam version in Clio hack. ([#623](https://github.com/broadinstitute/wfl/pull/623))
- [Back up to uberdeps 1.0.4 because 1.1.4 doesn't work for WFL yet.](https://github.com/broadinstitute/wfl/commit/eac6b875c3c935577252719c1afec75907646bb1)
- Note the changes over the already-merged `/tbl/release-0.20.1/` branch.
- `uberdeps/uberjar` fails silently, and none of our tests runs against the deployed jar.
[GH-1691]: https://broadinstitute.atlassian.net/browse/GH-1691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [GH-1691] Deploy WFL 0.20.1 to pick up AoU and SG/GDC fixes.

- api/test/resources/datasets/illumina-genotyping-array.json
- api/test/resources/datasets/testing-dataset.json
- api/test/wfl/integration/firecloud_test.clj
Resolve broken CI issues
- Updates datarepo calls to unset the `dedicatedIngestServiceAccount` field
- Updates historical Workflow Run to target a non-archived run
> WM-2582, WM-2583: Resolve CI issues
