ui/package-lock.json
ui/package.json

- Fix security risk around minimist following instructions from Github.
- No changes.

Fix security risk around minimist.

---

database/changelog.xml
database/changesets/20200316_ExternalWholeGenomeReprocessingEnum.xml
database/changesets/20200317_ExternalWholeGenomeReprocessingTable.xml
src/zero/boot.clj

```
2020-03-19 16:10:33.155 EDT [23812] ERROR:  ALTER TYPE ... ADD cannot run inside a transaction block
2020-03-19 16:10:33.155 EDT [23812] STATEMENT:  ALTER TYPE pipeline ADD VALUE 'ExternalWholeGenomeReprocessing'
```

Work around the PostgreSQL enum transaction error.

---

docs/md/dev-process.md
docs/mkdocs.yml

- Add dev-process doc per discussion during retro.
- Take a look at the page: https://broadinstitute.github.io/wfl/dev-process/

Add Dev-process document.

---

.github/workflows/doc-site.yml
docs/md/README.md
docs/mkdocs.yml
docs/requirements.txt

- A Github Action for building and publishing the docs to our doc site automatically
- Unfortunately this PR is not easy to be tested until we merge it and see how it goes. I will fix it if it turns out to be not working. I made a testing commit to trigger it: https://github.com/broadinstitute/wfl/runs/586811314?check_suite_focus=true

A Github Action for building and publishing the docs to our doc site automatically

---

.github/workflows/docker_publish.yml

Ra master publish docker

---

helm/wfl/.helmignore
helm/wfl/Chart.yaml
helm/wfl/templates/NOTES.txt
helm/wfl/templates/_helpers.tpl
helm/wfl/templates/configmap.yaml
helm/wfl/templates/deployment.yaml
helm/wfl/templates/ingress.yaml
helm/wfl/templates/pod-running-policy.yaml
helm/wfl/templates/role.yaml
helm/wfl/templates/rolebinding.yaml
helm/wfl/templates/service.yaml
helm/wfl/templates/serviceaccount.yaml
helm/wfl/templates/tests/test-connection.yaml
helm/wfl/values.yaml
src/zero/api/routes.clj
ui/src/components/TopBar.vue

- https://broadinstitute.atlassian.net/jira/software/projects/GH/boards/530?selectedIssue=GH-706
- Also see:
- Create Helm Charts for WFL deployment.
- Docker images of WFL (with tag `test` have been manually pushed to DockerHub)
- The `/swagger` endpoint of WFL has been slightly modified.
- Please see the deployed and running version here: https://workflow-launcher.gotc-dev.broadinstitute.org/
Note:
- In this PR the deployment of API and UI is on the same pod, this is easy to implement as a first iteration but will bring scaling issues in the future, for the API is stateful. 
~~- The Swagger UI (https://workflow-launcher.gotc-dev.broadinstitute.org/swagger) is still not working on the deployed server, I'd like to get some help around it if possible. (Weirdly …

Create WFL Helm charts.

---

src/zero/api/routes.clj
ui/public/index.html
ui/src/App.vue
ui/src/components/TopBar.vue
ui/src/router/index.js
ui/src/views/Dashboard.vue

- Fix Dashboard.
- Fix several places that still have "Zero".
- Remove redundant code and Google Auth button.
- Update the API `/version` endpoint to separate pipeline-versions and system versions.

Some ui fixes during hornet engineering time

---

helm/wfl/Chart.yaml
helm/wfl/templates/configmap.yaml

- Fix an issue with Apache config that prevents UI from refreshing
- No changes.
- No if you go to https://workflow-launcher.gotc-dev.broadinstitute.org/modules directly, instead of getting rejected by Apache, you should see the page. Refreshing also works.

Fix an issue with Apache config that prevents UI from refreshing

---

docs/md/deployment.md
docs/mkdocs.yml

- Add deployment docs.
- Add deployment docs.

Add deployment docs.

---

.github/workflows/helmchart-release.yml
.github/workflows/helmchart-test.yml
ct.yaml
helm/wfl/Chart.yaml

- https://broadinstitute.atlassian.net/browse/GH-777
- Updated the workflow for chart release to read token from vault
- Added workflow chart test
- Bumped version of wfl helm chart to test
- the reviewer should confirm the PR triggered the workflow chart test and it's ok
- the reviewer should confirm the same changes applied to repo gotc-deploy for workflow chart releaser have been applied in repo wfl
- secrets should contain roleID, secretID, vault_addr
- secret CR_TOKEN should be removed

Gh-777 update helmchart workflow wfl

---

docs/md/deployment.md
helm/wfl/Chart.yaml
helm/wfl/values.yaml
ops/cli.py
src/zero/main.clj

https://broadinstitute.atlassian.net/browse/GH-803

GH-803: Fix typos.

---

.github/workflows/pr-test.yml
docs/md/README.md

- https://broadinstitute.atlassian.net/browse/GH-738
- Add a Github Action for running Unit Tests per PR.
- Add a naive build board to the readme.

GH-738: Run Unit Tests per PR

---

helm/wfl/Chart.yaml
helm/wfl/values.yaml

Fix typos in values.yaml

---

ops/cli.py

- https://broadinstitute.atlassian.net/jira/software/projects/GH/boards/530?selectedIssue=GH-848
- Fix the docker command for liquibase migration.
- Add a connect (to cloudsql) command for convenience.

Fix the docker command for liquibase migration.

---

cloud_function/tests/upload_test_files.py

Add a script to make QA/testing the cloud function easier.
The script copies all of the files for an arrays sample into the dev aou input bucket, which triggers the cloud function. When all of the files are uploaded, the cloud function will submit an arrays workflow using the workflow launcher.

[GH-837] Add helper script for testing cloud fn

---

cloud_function/tests/upload_test_files.py

Fix a small bug in the upload_test_files.py helper script.
- No changes.

[GH-837] Fix upload_test_files.py

---

cloud_function/deploy.sh

Required for https://broadinstitute.atlassian.net/jira/software/projects/GH/boards/530?selectedIssue=GH-852
Specify the AOU WFL url to use when deploying this cloud function to the broad-aou project.

[GH-852] Update cloud fn deploy script

---

cloud_function/tests/upload_test_files.py

Made some changes to the `upload_test_files.py` helper script to make it easier to QA https://broadinstitute.atlassian.net/browse/GH-852
Pass in the bucket name as a parameter to the script 

[GH-852] Parameterize bucket name in upload script

---

cloud_function/deploy.sh

- https://broadinstitute.atlassian.net/browse/GH-877
- https://broadinstitute.atlassian.net/browse/GH-873
- Consequence of https://github.com/broadinstitute/gotc-deploy/pull/114
- Change bucket location and WFL URL to what they will be
- We'll be able to deploy the cloud function here as soon as the move is complete

[GH-877] Change dev input bucket location

---

cloud_function/tests/upload_test_files.py

Update the helper script to manually test the cloud fn (follow-up to https://github.com/broadinstitute/wfl/pull/95)
Add "chipname" to the upload path to match PTC behavior. 

[GH-883] Update test sample upload paths

---

ops/cli.py

- https://broadinstitute.atlassian.net/browse/GH-877
- Fix reading from the helm values file
- Add space to the prompt
- Be more specific about the namespace

[GH-877] small deploy script fixes

---

ops/cli.py
ops/render_ctmpl.py

- https://broadinstitute.atlassian.net/browse/GH-877
- Several small bugfixes
- Biggest thing was now passing the WFL_DB_URL through to the template
- This version was used to deploy WFL, I don't know that we'll get much more verification of it working than that.

[GH-877] More small deploy script fixes

---

docs/md/sandbox.md
docs/mkdocs.yml

- https://broadinstitute.atlassian.net/browse/GH-797
- Adds sandbox.md to document my process in https://github.com/broadinstitute/gotc-deploy/pull/121
- Add logging.md and sandbox.md to the web page sidebar because I just realized how that part worked
- Someone else should follow the instructions and see if they work

[GH-797] Sandbox documentation

---

api/src/zero/module/aou.clj
api/test/zero/unit/aou_module_test.clj

- https://broadinstitute.atlassian.net/browse/GH-896
- No changes.

[GH-896] WFL can add arrays sample information to the workflows as labels

---

api/src/zero/module/aou.clj
api/test/zero/unit/aou_module_test.clj

- https://broadinstitute.atlassian.net/browse/GH-898
- Remove the confusing default chip-metadata inputs from the codebase.
- Genotype concordance inputs are optional now.
- Add unit tests accordingly.

[GH-898] Separate mandatory and optional inputs.

---

cloud_function/deploy.sh

Ticket: https://broadinstitute.atlassian.net/browse/GH-904
Pass in `--retry` flag when deploying the cloud function
See: https://cloud.google.com/sdk/gcloud/reference/functions/deploy

[GH-904] Enable cloud function retries

---

cloud_function/README.md
cloud_function/tests/upload_test_files.py

The arrays workflow requires a valid chip well barcode to run, so this helper test script needs to change the analysis version number for each run instead. 
- Randomize the analysis version number for the files that get uploaded to the arrays input bucket

Fix cloud function helper test script

---

api/test/zero/tools/endpoints.clj
api/test/zero/tools/workloads.clj
database/changesets/20200827_ExternalWholeGenomeReprocessingTable.xml

Apply the db changes to existing tables as well, otherwise liquibase will throw an error when trying to apply this changeset.
- No changes.

[GH-818] Make WGS db changes CASCADE

---

.github/workflows/release_latest_version.yml

- https://broadinstitute.atlassian.net/browse/GH-914
- `clojure` wasn't available in the job, this should fix it
- Manually run the job

Setup Java and Clojure for real

---

.github/workflows/pr-test.yml
cloud_function/main.py

- https://broadinstitute.atlassian.net/jira/software/projects/GH/boards/530?selectedIssue=GH-939
Looking at the Google Cloud Bucket implementation, which only implements `__repr__` but `__str__`
```python
def __repr__(self):
return "<Bucket: %s>" % (self.name,)
```
we cannot simply use `str(Bucket())` to stringify the bucket name, which is why the test is failing. 
We should run Cloud Function Unit Tests per PR as well, which should have caught this bug earlier.
- Run `pytest tests/` again.

[GH-939] Fix issues with Cloud Function

---

.github/workflows/release_latest_version.yml

- https://broadinstitute.atlassian.net/browse/GH-914
- Also setup gcloud.
- This code is copied from the [PR test job](https://github.com/broadinstitute/wfl/blob/master/.github/workflows/pr-test.yml#L67), so code review for this PR is mainly sanity-checking that I didn't screw that copy up
- Will have to wait until we bump WFL again to see if it works.

[GH-914] Also setup gcloud in release job

---

api/src/wfl/wfl.clj

Fixes: https://broadinstitute.atlassian.net/browse/GH-952
Set a bogus commit value for testing against a local WFL server.

[GH-952] Add default version commit for testing

---

api/deps.edn

- https://broadinstitute.atlassian.net/browse/GH-980
- No changes.

GH-980: Bring WFL's deps.edn up to date with new liquibase alias.

---

api/build.boot
api/deps.edn
api/src/wfl/service/postgres.clj
api/test/wfl/tools/liquibase.clj

We don't need a product dependency on liquibase. I'm moving it to a test tool.

[GH-980] move liquibase dependency to tests

---

api/src/wfl/api/handlers.clj
api/src/wfl/api/routes.clj
api/src/wfl/service/postgres.clj

- https://broadinstitute.atlassian.net/browse/GH-968
- Cherry-pick https://github.com/broadinstitute/wfl/pull/150
- Resolve merge conflicts.
- When I ran the integration tests, `wfl.integration.v1-endpoint-test/test-start-wgs-workload` failed due to a "pipeline-ish" problem: https://jmui.gotc-dev.broadinstitute.org/jobs/21c0a914-63fa-4ca6-bd1e-09dbf215c76f. Would be appreciated if anyone could help take a look.

[GH-968] Forward-patch hotfix v0.1.11

---

api/test/wfl/system/module_test.clj

Ticket: https://broadinstitute.atlassian.net/browse/GH-995
Fix getting the cromwell workflow uuids started by `test-append-to-aou-workload`

[GH-995] Fix AoU system test

---

.github/workflows/release_latest_version.yml
ui/src/views/Dashboard.vue

This is on WFL UI's dashboard, I realized the existing entry was confusing.
- Old:
- New:
- If you'd like to see it yourself you can built with the same `USER=` thing and use `./ops/server.sh`

Make version author on dashboard more clear

---

.github/workflows/helmchart-release.yml
.github/workflows/pr-test.yml
.github/workflows/release_latest_version.yml

- https://broadinstitute.atlassian.net/browse/GH-1009
- Use the new environment files
- This should result in no new test failures (this is a no-op change)

[GH-1009] Change to environment files

---

ui/package-lock.json
ui/package.json

- See https://github.com/broadinstitute/wfl/network/alert/ui/package-lock.json/node-forge/open
- I followed the instructions from dependabot and ran `npm audit fix`.

Security vulnerability fixes.

---

docs/md/dev-sandbox.md

- I forgot to include a part of one of the commands, this adds it.

Fix a typo in the sandbox docs

---

.github/workflows/pr-test.yml
.github/workflows/release_latest_version.yml
api/src/wfl/api/handlers.clj
api/src/wfl/api/spec.clj
api/src/wfl/boot.clj
api/src/wfl/main.clj
api/src/wfl/module/aou.clj
api/src/wfl/module/xx.clj
api/src/wfl/references.clj
api/src/wfl/service/cromwell.clj
api/src/wfl/util.clj
api/test/wfl/integration/xx_pipeline_test.clj
api/test/wfl/system/v1_endpoint_test.clj
api/test/wfl/tools/endpoints.clj
api/test/wfl/tools/fixtures.clj
api/test/wfl/tools/liquibase.clj
api/test/wfl/tools/workloads.clj
api/test/wfl/unit/utils_test.clj
api/test/wfl/unit/xx_test.clj
database/changelog.xml
database/changesets/20200909_ExternalExomeReprocessing.xml
docs/md/external-exome-reprocessing.md
docs/mkdocs.yml

Epic: https://broadinstitute.atlassian.net/browse/GH-913
Spec: https://broadinstitute.atlassian.net/wiki/spaces/GHConfluence/pages/1585905728/External+Exome+Reprocessing+in+Workflow-Launcher

[GH-819] External Exome Reprocessing

---

api/src/wfl/module/wgs.clj

- https://broadinstitute.atlassian.net/browse/GH-771
- Bump the WDL to 1.1.1 per Jessica Way
- Remove the fingerprinting since that is a per-sample thing (also per Jessica Way)
- Roll in Rex's v52 changes from GH-994 (#157)
- Is GH-994 still blocked? Are we not wanting this to be in because of where Cromwell v52 is and isn't?

[GH-771] WGS updates

---

docs/md/external-exome-reprocessing.md

Update the exomes documentation as suggested by @samanehsan, namely
- Include change in `items` schema (https://broadinstitute.atlassian.net/browse/GH-1013)
- Use the dev `workflow-launcher` url.

[GH-1011] update xx docs after changes to input `items`

---

ops/aou_cleanup/cleanup.py

Fixes some issues discovered during testing.
- Specify a google project when instantiating the gcloud storage client, otherwise it will use whatever default project you have set locally
- Change the `--dry_run` argument to `--apply`

[GH-978] Fixes to cleanup script

---

docs/md/workflow-options.md

-https://broadinstitute.atlassian.net/browse/GH-1014
- This file looked alright in markdown but when I saw it on the documentation site it looked way worse than I thought it would be -- just some small editing changes I'd like to be in before we sent it off to hOps

GH-1014 Documentation updates

---

api/src/wfl/module/wgs.clj
api/src/wfl/references.clj

Address feedback in https://github.com/broadinstitute/wfl/pull/221

update after @tbl3rd's comment

---

docs/md/dev-wgs.md
docs/md/workflow-options.md

Update docs after https://github.com/broadinstitute/wfl/pull/225

update docs removing id and items

---

api/test/wfl/integration/datarepo_test.clj

- https://broadinstitute.atlassian.net/browse/GH-1048
- No changes.  Really.  Almost no changes.
- Data Repo deployed a new steps runner. It won't fail the same way. Revisit this when it fails again.

[GH-1048] Fix the DataRepo test.

---

.github/workflows/release_latest_version.yml
CHANGELOG.md

2nd attempt at creating v0.4.0.

release/0.4.0 rc.2

---

docs/md/index.md
readme.md

- I followed the instructions from @jack-r-warren and https://intranet.broadinstitute.org/bits/service-catalog/websites-portals/personal-sites
- Click the updated badge (under VPN) and verify that the new HTML page works.

Transition the Hornet build board.

---

api/src/wfl/api/routes.clj

Log middleware exceptions better

---

api/src/wfl/api/routes.clj

Log middleware exceptions better (double submit)

---

api/src/wfl/boot.clj

Use updated environments. See https://broadinstitute.atlassian.net/browse/GH-1078

[GH-1078] use updated environments from pipeline_config

---

api/src/wfl/api/routes.clj

Currently, all exceptions are being logged as errors. This creates a lot of noise as some failures are expected (e.g. wrong pipeline, no such workflow etc)
In this change, I propose to make the logging less noisy for 0.4.2. We can consider an alternative solution for the main branch.

make error logging less noisy

---

api/src/wfl/module/wgs.clj

Fixes https://broadinstitute.atlassian.net/browse/GH-1082

[GH-1082] fix wrong cromwell queried in `wgs/skip-workflow?`

---

api/src/wfl/boot.clj

- https://broadinstitute.atlassian.net/browse/GH-1080
- Use https://github.com/broadinstitute/pipeline-config/commit/3f182c0b06ee5f2dfebf15ed8b12d513027878ae

[GH-1080] [Double-submit] Use updated environments.clj with gotc-prod being wgs-prod

---

CHANGELOG.md

Add change-log ahead of releasing wfl-0.4.2.

release 0.4.2-rc.1

---

api/src/wfl/boot.clj

- https://broadinstitute.atlassian.net/browse/GH-1080
- Use https://github.com/broadinstitute/pipeline-config/commit/3f182c0b06ee5f2dfebf15ed8b12d513027878ae

[GH-1080] Use updated environments.clj with gotc-prod being wgs-prod

---

api/test/wfl/integration/terra_test.clj

Ticket: https://broadinstitute.atlassian.net/browse/GH-1099
The ExternalWGS pipeline was removed from staging dockstore, so this test uses the "Arrays" pipeline instead.

[GH-1099] Fix terra integration test

---

api/test/wfl/integration/modules/wgs_test.clj
docs/md/directory-usage.md
docs/md/modules-wgs.md
docs/mkdocs.yml

- https://broadinstitute.atlassian.net/browse/GH-1069
- Adds a test for WGS supplying defaults (we didn't really document that anywhere solid)
- Updates WGS documentation (mention correct defaulting behavior and non-relative input paths)
- Adds new directory usage page

[GH-1069] Directory Usage Documentation

---

api/module.mk
api/src/wfl/build.clj
api/src/wfl/environments.clj
docs/md/index.md

- https://broadinstitute.atlassian.net/browse/GH-1103
- No changes.

GH-1103: Rename boot.clj to build.clj and fix what breaks.

---

api/deps.edn
ops/server.sh

- https://broadinstitute.atlassian.net/browse/GH-1107
- No changes.

GH-1107: Replace wfl link to build.boot.

---

docs/md/directory-usage.md
docs/md/modules-external-exome-reprocessing.md

- Nareh caught this, I think we should update it ASAP

Reference prod WFL in usage docs

---

ui/package-lock.json
ui/package.json

- https://github.com/broadinstitute/wfl/network/alert/ui/package-lock.json/highlight.js/open
- Update the deps as suggested.
- `npm run-script build` passed.

Update the versions of the highlighJS as suggested by dependabot.

---

.github/workflows/helmchart-release.yml
.github/workflows/pr-helm-lint.yml
helm/wfl/Chart.yaml
helm/wfl/templates/configmap.yaml

- https://broadinstitute.atlassian.net/browse/GH-1114
- Redo #178 

[GH-1114] Fix WFL's Helm chart releaser action

---

api/src/wfl/api/handlers.clj
api/src/wfl/api/spec.clj
api/src/wfl/build.clj
api/src/wfl/module/batch.clj
api/src/wfl/module/sg.clj
api/src/wfl/module/wgs.clj
api/src/wfl/references.clj
api/src/wfl/wdl.clj
api/test/wfl/integration/modules/sg_test.clj
api/test/wfl/system/v1_endpoint_test.clj
api/test/wfl/tools/workloads.clj
database/changelog.xml
database/changesets/20201216_GDCWholeGenomeSomaticSingleSample.xml

- https://broadinstitute.atlassian.net/browse/GH-1089
- Adds an SG module
- Change cromwell submission slightly to allow bypass of `util/make-options` (this allows us to use cromwell options to copy the outputs, since the WDL doesn't natively support it)
- Make WFL not fall over if the input zip process comes up empty
- Wire SG into the integration and system tests
- Tests pass. You can run this to trigger a workflow:
```bash
curl --location --request POST 'http://localhost:3000/api/v1/exec' \
--header 'Authorization: Bearer '$(gcloud auth print-access-token) \
--header 'Content-Type: application/json' \
--data-raw '{
"pipeline": "GDCWholeGenomeSomaticSingleSample",
"cromwell": "https://cromwell-gotc-auth.gotc-dev.broadinstitute.org",
"output": …
```

[GH-1089] SG module

---

docs/md/modules-retry-usage.md
docs/mkdocs.yml

- https://broadinstitute.atlassian.net/browse/GH-1127
- Add the page
- I put it under "Modules" in the sidebar because "Get Started" is just a page and "Readings" doesn't seem to be user-focused. Should I make a separate section for this and the directory usage page?

[GH-1127] Add docs for retrying failures

---

CHANGELOG.md

Prepare for release v0.5.0-rc1.

---

docs/md/modules-gp-arrays.md
docs/mkdocs.yml

https://broadinstitute.atlassian.net/browse/GH-1134
Update the WFL docs with a section on the `GPArrays` module

[GH-1134] Add docs for GPArrays module

---

ui/src/App.vue
ui/src/components/SideBar.vue
ui/src/views/Query.vue
ui/src/views/Workload.vue

- Fixed some warnings in the UI build.
- Removed redundant components (settings, help, etc.) from the page.

[Snack] Fix some bugs and warnings on the frontend

---

api/build/build.clj

- https://broadinstitute.atlassian.net/browse/GH-1123
- Update the pipeline-config commit to HEAD on /master/ again.

GH-1123: Update the environments commit. For the last time?

---

api/src/wfl/module/wgs.clj

- https://broadinstitute.atlassian.net/browse/GH-1200
- Double submit what's committed (and tagged) at `ed373b4c593bf25173e438aa8775acc1f7e072ba`

[GH-1200] Double submit hot-fix 0.5.2.

---

api/test/wfl/integration/firecloud_test.clj

Not exactly sure what's causing this, or if it's a real issue at
all. It failed twice (once locally and then in a PR) but now I
can't reproduce it at all.
I suspect that it's being caused by querying the submission before
the workflows have been queued but I have no real evidence to
support this. If it is what I think, getting the submission again
might mitigate the problem.

Add workaround for GH-1212.

---

api/src/wfl/environment.clj
helm/wfl/Chart.yaml
helm/wfl/values.yaml

- https://broadinstitute.atlassian.net/browse/GH-1196
- No changes.

GH-1191: Plumb WFL_CLIO_URL for production.

---

ops/cli.py

This is for ticket GH-1254. It updates the cli.py file to use helmfile iinstead of helm for deployment.
cli.py

Changing cli.py to reflect deployment from helmfile rather than helm

---

ops/cli.py

The purpose of this is to update the cli.py file to leverage helmfile rather than helm for deployments. In addition, since we are no longer using Jenkins mentions thereof have been removed. 
Verify that the syntax is correct and that nothing has been deleted which is otherwise needed.

Ra gh1254 cli changes

---

ops/cli.py

- https://broadinstitute.atlassian.net/browse/GH-1254
- No changes.

[GH-1254] Follow-up work to further fix the CLI script after it's moved to gotc-deploy

---

docs/md/index.md
docs/md/modules-sg.md
docs/mkdocs.yml

- https://broadinstitute.atlassian.net/browse/GH-1282
- Like it says.
- This is documentation.  Read it?

GH-1282: Document WFL's support for Somatic Genomes.

---

.github/workflows/pr-helm-lint.yml
.github/workflows/pr-test.yml
.github/workflows/release.yml
CHANGELOG.md
api/src/wfl/module/sg.clj
api/test/wfl/integration/modules/sg_test.clj
docs/md/dev-process.md
docs/md/dev-release.md
docs/md/index.md
docs/md/modules-sg.md
docs/mkdocs.yml
ops/cli.py

v0.6.0 -GDCWholeGenomeSomaticSingleSample pipeline support
See CHANGELOG.md for commits

v0.6.0 Release

---

CHANGELOG.md

Promoting the changes from `main` into `develop` or v0.6.0 release

Update CHANGELOG.md in `develop`

---

CHANGELOG.md

Update CHANGELOG.md in develop for new release

Merge v0.6.1 into develop

---

api/src/wfl/tsv.clj
api/test/wfl/unit/tsv_test.clj
docs/md/index.md

- https://broadinstitute.atlassian.net/browse/GH-1272
- Add readers and writers and parsers for Terra's idea of a TSV file.
- Add a unit test too.
- Might have been easier to code a parser/unparser from scratch.
- This is a bundle of hacks developed to avoid writing a parser to mimic Firecloud's.
- Run `time clojure -M:test --focus wfl.unit.tsv-test` for insight.
- Please tell me where we want to deploy this.
- I welcome suggestions.

GH-1272: Lists are not imported correctly into a Terra Workspace Entity

---

database/changesets/20210414_Sarscov2IlluminaFullTable.xml
docs/md/dev-process.md
docs/md/index.md
docs/mkdocs.yml
docs/readme.md

After interacting with snapshots via the Rawls API, I realized that we would also want to store the snapshot's reference ID (unique identifier for snapshot reference within Terra Workspace).  Previously we only stored the snapshot ID (unique identifier for snapshot within TDR).
In testing this change, I ran into issues with my local Postgres.  Thanks @rexwangcc for the help!  As such, this PR is mostly documentation changes reflecting my experience, along with fixing some oddities I encountered in my general onboarding.
Schema
- Added snapshot_reference_id to Sarscov2IlluminaFull table schema
Documentation
- Clarified order of operations when installing, using local Postgres
- Fixed broken intra-doc links
- Added docs readme with …

[GH-1215] Add snapshot_reference_id to Sarscov2IlluminaFull table schema

---

api/deps.edn
api/src/wfl/module/arrays.clj
api/src/wfl/service/firecloud.clj
api/src/wfl/service/rawls.clj
api/test/wfl/integration/datarepo_test.clj
api/test/wfl/integration/firecloud_test.clj
api/test/wfl/integration/modules/arrays_test.clj
api/test/wfl/integration/rawls_test.clj
api/test/wfl/system/cdc_covid19_surveillance_demo.clj
api/test/wfl/tools/fixtures.clj

add interactive script ahead of covid-19 demo 

---

api/src/wfl/module/covid.clj
api/test/wfl/tools/workloads.clj
api/test/wfl/unit/modules/covid_test.clj
database/changesets/20210422_TerraDataRepoSourceTable.xml

RR: https://broadinstitute.atlassian.net/browse/GH-1320
Adding a list of people who want to access to the snapshots we create to the source request.

[GH-1320] add snapshotReaders to tdr source

---

api/deps.edn

- Remove liquibase-core from build dependencies.
- Verify we can build WFL without it?

Remove liquibase-core from build dependencies.

---

api/src/wfl/api/spec.clj
api/src/wfl/module/covid.clj
api/src/wfl/util.clj
api/test/wfl/unit/spec_test.clj

See commits for more detailed information

[GH-1341][GH-1344] Various Bug Fixes for v0.7.0

---

api/src/wfl/api/spec.clj
api/test/wfl/integration/modules/covid_test.clj

RR: https://broadinstitute.atlassian.net/browse/GH-1356
Caused by https://github.com/metosin/reitit/issues/494
Fix as per https://broadinstitute.atlassian.net/browse/GH-1348
Included integration test for reitit coercions to catch this sooner.

[GH-1356] Fix Coercion Failure for TDR Snapshots Source

---

api/src/wfl/module/covid.clj

- https://broadinstitute.atlassian.net/browse/GH-1362
- Move docstring and document when true.
- Read the new docstring and ensure it is in the correct place.

Move docstring and document when true.

---

CHANGELOG.md

update changelog for v0.7.1

---

api/src/wfl/environment.clj
api/src/wfl/service/datarepo.clj
api/test/wfl/integration/datarepo_test.clj

- https://broadinstitute.atlassian.net/browse/GH-1294
- Migrate to use [dataset](https://data.terra.bio/datasets/4a5d30fe-1f99-42cd-998b-a979885dea00/query) in production TDR.
- Update some tests so they pass.
- Update the default ENV values accordingly.

[GH-1294] Migrate to use datasets in prod TDR

---

api/deps.edn
api/module.mk
api/src/wfl/executor.clj
api/src/wfl/module/covid.clj
api/src/wfl/service/firecloud.clj
api/src/wfl/stage.clj
api/src/wfl/tsv.clj
api/src/wfl/util.clj
api/test/wfl/integration/executor_test.clj
api/test/wfl/integration/modules/covid_test.clj
api/test/wfl/integration/source_test.clj
makerules/modules.mk

RR: https://broadinstitute.atlassian.net/browse/GH-1335
Doc-strings from https://github.com/broadinstitute/wfl/pull/451

[GH-1335] Move `Executor` Code to new Namespace

---

docs/md/executor.md

- https://broadinstitute.atlassian.net/browse/GH-1346
Forgot to push this return type hint to main executor documentation [PR](https://github.com/broadinstitute/wfl/pull/451).

Phoned a friend @tbl3rd to fix return type hint in executor docs

---

api/src/wfl/executor.clj
api/src/wfl/module/covid.clj
api/src/wfl/sink.clj
api/test/wfl/integration/datarepo_test.clj
api/test/wfl/integration/executor_test.clj
api/test/wfl/integration/modules/covid_test.clj
api/test/wfl/integration/sink_test.clj
api/test/wfl/system/cdc_covid19_surveillance_demo.clj
api/test/wfl/unit/modules/covid_test.clj
api/test/wfl/unit/sink_test.clj
docs/md/dev-process.md

- https://broadinstitute.atlassian.net/browse/GH-1326
And fleshed out developer debug documentation in response to a roadblock I encountered (thanks @tbl3rd for the linting tip!)

GH-1326 Move Sink code to new Namespace

---

api/src/wfl/api/spec.clj
api/src/wfl/module/all.clj
api/src/wfl/module/batch.clj
api/src/wfl/service/cromwell.clj
api/src/wfl/service/postgres.clj
api/src/wfl/sink.clj
api/src/wfl/util.clj
api/test/wfl/integration/datarepo_test.clj
api/test/wfl/integration/modules/covid_test.clj
api/test/wfl/system/automation_test.clj
api/test/wfl/tools/workloads.clj
api/test/wfl/unit/sink_test.clj

- https://broadinstitute.atlassian.net/browse/GH-1417
- Remove the synthetic string `"skipped"` status from cromwell support.
- Turns out `uuid-nil?` and so on supported only `"skipped"` so that's gone too.
- Fuss over specs a bit.
- Gleaned some lint that I noticed collecting.
- Ignore this for now because Ed doesn't want it yet.
- Ed says its OK to review this now.
- Diff this branch against `develop`?

GH-1417: Remove the "skipped" nil UUID Cromwell status hack.

---

docs/md/sink.md

RR: https://broadinstitute.atlassian.net/browse/GH-1416
Add section to `sink.md` describing how to configure workflow-launcher
to write outputs back to a terra datarepo dataset.

[GH-1416] Document DataRepo Sink

---

docs/md/usage-retry.md

- https://broadinstitute.atlassian.net/browse/GH-1395
- Document that /retry in not implemented.

GH-1395: Document the new WFL retry capability for users.

---

docs/mkdocs.yml
docs/requirements.txt

- Mkdocs updates that improve the doc nav and security holes.

Mkdocs updates that improve the doc nav and security holes.

---

.github/workflows/nightly.yml
api/module.mk
makerules/modules.mk

- Add a nightly system test against dev WFL, which can also be triggered manually.
- Until we deploy the latest set of changes to `dev WFL`, this system will not pass :(

Add a nightly system test against dev WFL

---

readme.md

- Add a badge for WFL nightly test.
- No changes.
- The nightly testing is expected to fail at this point since the deployed WFL's watcher spec conflicts with what the nightly test is expecting.

Add a badge for WFL nightly test.

---

api/src/wfl/module/covid.clj
docs/md/staged-workload.md

- https://broadinstitute.atlassian.net/browse/GH-1462
- Make :watchers consistently optional.

GH-1462: Make :watchers key always optional.

---

api/src/wfl/executor.clj
api/test/wfl/integration/executor_test.clj

- https://broadinstitute.atlassian.net/browse/GH-1517
I added an integration test to codify the manual verification I performed for https://github.com/broadinstitute/wfl/pull/527
(Resharing for context) When attempting to submit a snapshot, if the method config's version doesn't match what we expect, we log an error rather than throw an exception. This allows submissions to move forward without Hornet developer intervention. In the edge case where a method configuration change caused workflow(s) to fail, we will have the record of the error log and Stackdriver alert to aide in debugging.

[GH-1517] Add automated test for updating method configurations with mismatched versions

---

docs/md/dev-logging.md

Needed to add an explanation on how to change logging level to the logging documentation.
https://broadinstitute.atlassian.net/browse/GH-1506
- Add documentation to `dev-logging.md`
- Read the new documentation for accuracy.

[GH-1506] Add documentation for changing the logging level

---

api/src/wfl/module/aou.clj

- https://broadinstitute.atlassian.net/browse/GH-1526
- `:release "Arrays_v2.6.0"`

GH-1526: Bump the Arrays WDL release to 2.6.0

---

api/src/wfl/module/aou.clj

- https://broadinstitute.atlassian.net/browse/GH-1586
- Bump AoU Arrays WDL to Arrays_v2.6.3 to pick up bug fix.

[GH-1586] Run AoU pipeline with the Arrays_v2.6.3 WDL.

---

api/src/wfl/util.clj

- https://broadinstitute.atlassian.net/browse/GH-1609
- Make `do-or-nil log` at `"DEBUG"` severity.

[GH-1609] Make do-or-nil log at :debug level.

---

api/src/wfl/module/sg.clj

- https://broadinstitute.atlassian.net/browse/GH-1666
- Pick up GDCWholeGenomeSomaticSingleSample_v1.3.0 in sg module.

[GH-1666] Pick up GDCWholeGenomeSomaticSingleSample_v1.3.0 in sg module.

---

api/src/wfl/executor.clj
api/src/wfl/service/firecloud.clj
api/test/wfl/integration/executor_test.clj
api/test/wfl/unit/slack_test.clj
database/changelog.xml
database/changesets/20220523_AddMemoryRetryMultiplierColumn.xml
docs/md/staged-executor.md

- https://broadinstitute.atlassian.net/browse/GH-1654
- Add a `memory_retry_multiplier` column to the `TerraExecutor` table.
- Map `:memoryRetryMultiplier` workload `executor` attribute to the new column.
- Test that the new attribute round-trips through the database.

[GH-1654] Admit memory retry multiplier.

---

api/src/wfl/executor.clj

- https://broadinstitute.atlassian.net/browse/GH-1671
- The `userComment` param is optional and must appear last.

[GH-1671] create-submission! swaps arguments to submit-method.

---

api/src/wfl/module/xx.clj

- https://broadinstitute.atlassian.net/browse/GH-1686
- No changes.

[GH-1686] ExternalExomeReprocessing_v3.1.7 to pick up picard-cloud:2.26.10.

---

api/src/wfl/module/sg.clj

[- WM-2560](https://broadworkbench.atlassian.net/browse/WM-2560)
- Update GDCWholeGenomeSomaticSingleSample to 1.3.1

WM-2560: Update GDCWholeGenomeSomaticSingleSample to 1.3.1
